/*
 * JScience - Java(TM) Tools and Libraries for the Advancement of Sciences.
 * Copyright (C) 2025-2026 - Silvere Martin-Michiellot and Gemini AI (Google DeepMind)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/*
 * SpectrumCanvas.java
 *
 * Created on October 23, 2001, 4:03 PM
 */
package org.jscience.physics.nuclear.kinematics.nuclear.gui;

import java.awt.*;
import java.awt.font.FontRenderContext;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;

import javax.swing.*;


/**
 * 
DOCUMENT ME!
 *
 * @author org.jscience.physics.nuclear.kinematics
 */
public class SpectrumCanvas extends JPanel {
    /**
     * DOCUMENT ME!
     */
    double[] radii;

    /**
     * DOCUMENT ME!
     */
    double[] Ex;

    /**
     * DOCUMENT ME!
     */
    RadiusRange range;

/**
     * Creates new form SpectrumCanvas
     */
    public SpectrumCanvas(RadiusRange rr) {
        initComponents();
        this.range = rr;
        setBackground(Color.white);
        setBorder(BorderFactory.createLineBorder(Color.blue, 1));
        setOpaque(true);
    }

    /**
     * DOCUMENT ME!
     *
     * @param radii DOCUMENT ME!
     */
    public void setRadii(double[] radii) {
        this.radii = radii;
    }

    /**
     * DOCUMENT ME!
     *
     * @param Ex DOCUMENT ME!
     */
    public void setEx(double[] Ex) {
        this.Ex = Ex;
    }

    /**
     * This method is called from within the constructor to initialize
     * the form. WARNING: Do NOT modify this code. The content of this method
     * is always regenerated by the Form Editor.
     */
    private void initComponents() { //GEN-BEGIN:initComponents
        setLayout(new java.awt.BorderLayout());
    } //GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param graphics DOCUMENT ME!
     */
    public void paintComponent(Graphics graphics) {
        Line2D line;

        //System.out.println("painting with rho from "+range.getRhoMin()+" to "+
        //range.getRhoMax());
        Graphics2D g2 = (Graphics2D) graphics;
        FontRenderContext frc = g2.getFontRenderContext();
        Dimension d = getSize();
        double length = range.getRhoMax() - range.getRhoMin();
        //g2.setPaint(Color.blue);
        //g2.draw(new Line2D.Double(0,0,d.width,0));
        //g2.draw(new Line2D.Double(d.width,0,d.width,d.height));
        //g2.draw(new Line2D.Double(d.width,d.height,0,d.height));
        //g2.draw(new Line2D.Double(0,d.height,0,0));
        g2.setPaint(Color.darkGray);

        double lastXcoord = d.width;

        for (int i = 0; i < radii.length; i++) {
            //x coordinate from left
            if ((radii[i] > range.getRhoMin()) &&
                    (radii[i] < range.getRhoMax())) {
                String sEx = Ex[i] + " ";
                double xfrac = (radii[i] - range.getRhoMin()) / length;
                double xcoord = xfrac * d.width;
                double diff = lastXcoord - xcoord;
                Rectangle2D stringBounds = g2.getFont().getStringBounds(sEx, frc);
                double lineBottom;

                if (diff >= stringBounds.getWidth()) {
                    g2.drawString(sEx, (float) xcoord,
                        (float) (d.height - (stringBounds.getHeight() / 10)));
                    lastXcoord = xcoord;
                    lineBottom = d.height - stringBounds.getHeight();
                } else {
                    lineBottom = d.height - (2 * stringBounds.getHeight());
                }

                line = new Line2D.Double(xcoord, 0, xcoord, lineBottom);
                g2.draw(line);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
