/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jscience_jni_NativeDeviceBridge */

#ifndef _Included_org_jscience_jni_NativeDeviceBridge
#define _Included_org_jscience_jni_NativeDeviceBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jscience_jni_NativeDeviceBridge
 * Method:    connectDevice
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jscience_jni_NativeDeviceBridge_connectDevice
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_jscience_jni_NativeDeviceBridge
 * Method:    disconnectDevice
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_jscience_jni_NativeDeviceBridge_disconnectDevice
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_jscience_jni_NativeDeviceBridge
 * Method:    readSensorValue
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_org_jscience_jni_NativeDeviceBridge_readSensorValue
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
