/*
 * JScience - Java(TM) Tools and Libraries for the Advancement of Sciences.
 * Copyright (C) 2025-2026 - Silvere Martin-Michiellot and Gemini AI (Google DeepMind)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.jscience.architecture.lift;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;


/**
 * This file is licensed under the GNU Public Licens (GPL).<br>
 * This is a {@link PassengerGenerator} that generates {@link Passenger}s from
 * a file that has the same format as the file generated by {@link
 * LoggerPassengerProcessor}
 *
 * @author Nagy Elemer Karoly (eknagy@users.sourceforge.net)
 * @version $Revision: 1.4 $ $Date: 2007-10-23 18:13:51 $
 */
public class FileBasedPassengerGenerator extends PassengerGenerator {
    /**
     * DOCUMENT ME!
     */
    private int CurrentTick = -1;

    /**
     * DOCUMENT ME!
     */
    private int From = -1;

    /**
     * DOCUMENT ME!
     */
    private int To = -1;

    /**
     * DOCUMENT ME!
     */
    private BufferedReader BR;

/**
     * Constructor
     */
    public FileBasedPassengerGenerator(String InputFile)
        throws Exception {
        try {
            if (!((new File(InputFile)).getCanonicalPath()
                       .startsWith((new File(".")).getCanonicalPath()))) {
                throw new RuntimeException("ERROR! Illegal filename");
            }

            FileInputStream FIS = new FileInputStream("data/jlesa/" +
                    InputFile);
            InputStreamReader ISR = new InputStreamReader(FIS);

            BR = new BufferedReader(ISR);
        } catch (Exception E) {
            throw E;
        }
    }

    /**
     * {@link Tickable}
     *
     * @throws RuntimeException DOCUMENT ME!
     */
    public void Tick() {
        try {
            if (CurrentTick != -2) {
                while (CurrentTick < World.getTotalTicks()) {
                    String AL = BR.readLine();

                    if (AL == null) {
                        CurrentTick = -2;

                        break;
                    } else {
                        String[] Splitted = AL.split(" ");

                        if (Splitted.length < 2) {
                            throw new RuntimeException("Illegal formtat!");
                        }

                        String[] FromTo = Splitted[1].split(":");

                        if (Splitted.length < 2) {
                            throw new RuntimeException("Illegal formtat!");
                        }

                        CurrentTick = Integer.parseInt(Splitted[0]);
                        From = Integer.parseInt(FromTo[0]);
                        To = Integer.parseInt(FromTo[1]);
                    }
                }

                if (CurrentTick == World.getTotalTicks()) {
                    //					System.err.println("Tick, F,T: " + CurrentTick + ", " + From + ", " + To);
                    Passengers.add(new Passenger(From, To));
                    CurrentTick = -1;
                    Tick();
                }
            }
        } catch (Exception E) {
            throw new RuntimeException(E);
        }
    }

    /**
     * {@link Tickable}
     *
     * @return DOCUMENT ME!
     */
    public String getName() {
        return ("FileBasedPassengerGenerator");
    }

    /**
     * {@link Tickable}
     *
     * @return DOCUMENT ME!
     */
    public String getVersion() {
        return ("0.0.1");
    }
}
