package org.jscience.architecture.lift;

import java.util.ArrayList;


/**
 * This file is licensed under the GNU Public Licens (GPL).<br>
 * This should be the father of all entities that generate {@link Passenger}s.
 *
 * @author Nagy Elemer Karoly (eknagy@users.sourceforge.net)
 * @version $Revision: 1.4 $ $Date: 2007-10-23 18:13:52 $
 *
 * @see Passenger
 * @see PassengerProcessor
 */
public abstract class PassengerGenerator extends Tickable {
    /** The {@code Passenger}s generated so far. */
    protected final ArrayList Passengers;

/**
     * Constructor.
     */
    public PassengerGenerator() {
        super();
        Passengers = new ArrayList(128);
    }

    /* Tickable */
    public String getName() {
        return ("PassengerGenerator");
    }

    /**
     * Returns the {@link Passenger}s generated by this {@code
     * PassengerGenerator}. The {@link World} will delete the {@link
     * Passenger}s from the returned {@link java.util.ArrayList}.
     *
     * @return DOCUMENT ME!
     */
    public ArrayList getGeneratedPassengers() {
        return Passengers;
    }
}
