/*
 * JScience - Java(TM) Tools and Libraries for the Advancement of Sciences.
 * Copyright (C) 2025-2026 - Silvere Martin-Michiellot and Gemini AI (Google DeepMind)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.jscience.architecture.lift;

import java.util.ArrayList;


/**
 * This file is licensed under the GNU Public Licens (GPL).<br>
 * This should be the father of all entities that generate {@link Passenger}s.
 *
 * @author Nagy Elemer Karoly (eknagy@users.sourceforge.net)
 * @version $Revision: 1.4 $ $Date: 2007-10-23 18:13:52 $
 *
 * @see Passenger
 * @see PassengerProcessor
 */
public abstract class PassengerGenerator extends Tickable {
    /** The {@code Passenger}s generated so far. */
    protected final ArrayList Passengers;

/**
     * Constructor.
     */
    public PassengerGenerator() {
        super();
        Passengers = new ArrayList(128);
    }

    /* Tickable */
    public String getName() {
        return ("PassengerGenerator");
    }

    /**
     * Returns the {@link Passenger}s generated by this {@code
     * PassengerGenerator}. The {@link World} will delete the {@link
     * Passenger}s from the returned {@link java.util.ArrayList}.
     *
     * @return DOCUMENT ME!
     */
    public ArrayList getGeneratedPassengers() {
        return Passengers;
    }
}
