// autogenerated file 
package org.jscience.physics.fluids.dynamics;

/**
 * DOCUMENT ME!
 *
 * @author $author$
 * @version $Revision: 1.2 $
 */
public class CompiledData {
    /** DOCUMENT ME! */
    public static final String DATE = "mar nov 27 22:39:57 CET 2001";

    /** DOCUMENT ME! */
    public static final int REVISION = 1381;

    /** DOCUMENT ME! */
    public static final boolean VERBOSE = false;

    /** DOCUMENT ME! */
    public static final String VERSION = "2.1.java";
}
