/*
 * JScience - Java(TM) Tools and Libraries for the Advancement of Sciences.
 * Copyright (C) 2025-2026 - Silvere Martin-Michiellot and Gemini AI (Google DeepMind)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.jscience.mathematics.logic.connectors;

import java.io.IOException;

/**
 * Exporter for the Coq Proof Assistant.
 * <p>
 * Generates Coq vernacular (.v) files.
 * </p>
 *
 * @author Silvere Martin-Michiellot
 * @author Gemini AI (Google DeepMind)
 * @since 1.0
 */
public class CoqExporter implements FormalSystemExporter {

    @Override
    public void exportSystem(java.util.Map<String, Object> system, java.io.Writer writer) throws IOException {
        String name = (String) system.getOrDefault("module", "GeneratedModule");
        writer.write("(* Generated by JScience CoqExporter *)\n");
        writer.write("Module " + name + ".\n\n");

        // Iterate over axioms and theorems if present
        if (system.containsKey("axioms")) {
            @SuppressWarnings("unchecked")
            java.util.Map<String, String> axioms = (java.util.Map<String, String>) system.get("axioms");
            for (java.util.Map.Entry<String, String> entry : axioms.entrySet()) {
                writer.write("Axiom " + entry.getKey() + " : " + entry.getValue() + ".\n");
            }
        }

        writer.write("\nEnd " + name + ".\n");
    }

    @Override
    public String getFileExtension() {
        return ".v";
    }
}


