package org.jscience.mathematics.logic.connectors;

import java.io.IOException;

/**
 * Exporter for the Coq Proof Assistant.
 * <p>
 * Generates Coq vernacular (.v) files.
 * </p>
 * 
 * @author Silvere Martin-Michiellot
 * @author Gemini AI (Google DeepMind)
 * @since 1.0
 */
public class CoqExporter implements FormalSystemExporter {

    @Override
    public void exportSystem(java.util.Map<String, Object> system, java.io.Writer writer) throws IOException {
        String name = (String) system.getOrDefault("module", "GeneratedModule");
        writer.write("(* Generated by JScience CoqExporter *)\n");
        writer.write("Module " + name + ".\n\n");

        // Iterate over axioms and theorems if present
        if (system.containsKey("axioms")) {
            @SuppressWarnings("unchecked")
            java.util.Map<String, String> axioms = (java.util.Map<String, String>) system.get("axioms");
            for (java.util.Map.Entry<String, String> entry : axioms.entrySet()) {
                writer.write("Axiom " + entry.getKey() + " : " + entry.getValue() + ".\n");
            }
        }

        writer.write("\nEnd " + name + ".\n");
    }

    @Override
    public String getFileExtension() {
        return ".v";
    }
}
