/*
 * JScience - Java(TM) Tools and Libraries for the Advancement of Sciences.
 * Copyright (C) 2025 - Silvere Martin-Michiellot and Gemini AI (Google DeepMind)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.jscience.mathematics.structures.groups;

/**
 * A group is a set with an associative binary operation, an identity element,
 * and inverse elements.
 * <p>
 * Groups are fundamental in mathematics, appearing in geometry, number theory,
 * physics (symmetries), and many other areas.
 * </p>
 *
 * <h2>Mathematical Definition</h2>
 * <p>
 * A group (G, Ã¢Ë†â€”) must satisfy:
 * <ol>
 * <li><strong>Closure</strong>: Ã¢Ë†â‚¬ a, b Ã¢Ë†Ë† G: a Ã¢Ë†â€” b Ã¢Ë†Ë† G</li>
 * <li><strong>Associativity</strong>: Ã¢Ë†â‚¬ a, b, c Ã¢Ë†Ë† G: (a Ã¢Ë†â€” b) Ã¢Ë†â€” c = a Ã¢Ë†â€” (b Ã¢Ë†â€”
 * c)</li>
 * <li><strong>Identity</strong>: Ã¢Ë†Æ’ e Ã¢Ë†Ë† G such that Ã¢Ë†â‚¬ a Ã¢Ë†Ë† G: e Ã¢Ë†â€” a = a Ã¢Ë†â€” e =
 * a</li>
 * <li><strong>Inverse</strong>: Ã¢Ë†â‚¬ a Ã¢Ë†Ë† G, Ã¢Ë†Æ’ aÃ¢ÂÂ»Ã‚Â¹ Ã¢Ë†Ë† G such that: a Ã¢Ë†â€” aÃ¢ÂÂ»Ã‚Â¹ = aÃ¢ÂÂ»Ã‚Â¹ Ã¢Ë†â€” a
 * = e</li>
 * </ol>
 * </p>
 *
 * <h2>Examples</h2>
 * <ul>
 * <li>(Ã¢â€žÂ¤, +) - Integers with addition</li>
 * <li>(Ã¢â€žÅ¡\{0}, Ãƒâ€”) - Non-zero rationals with multiplication</li>
 * <li>(SÃ¢â€šÆ’, Ã¢Ë†Ëœ) - Symmetric group (permutations of 3 elements)</li>
 * <li>(Ã¢â€žÂÃ¢ÂÂ¿, +) - Real vectors with addition</li>
 * </ul>
 *
 * <h2>Special Cases</h2>
 * <ul>
 * <li><strong>Abelian Group</strong>: Commutative (a Ã¢Ë†â€” b = b Ã¢Ë†â€” a)</li>
 * <li><strong>Cyclic Group</strong>: Generated by single element</li>
 * <li><strong>Simple Group</strong>: No non-trivial normal subgroups</li>
 * </ul>
 *
 * <h2>Usage</h2>
 *
 * @author Silvere Martin-Michiellot
 * @author Gemini AI (Google DeepMind)
 * @since 1.0
 */
public interface Group<E> extends Monoid<E> {

    /**
     * Returns the inverse of the given element.
     * <p>
     * For element a, returns aÃ¢ÂÂ»Ã‚Â¹ such that: a Ã¢Ë†â€” aÃ¢ÂÂ»Ã‚Â¹ = aÃ¢ÂÂ»Ã‚Â¹ Ã¢Ë†â€” a = e (identity).
     * </p>
     * 
     * @param element the element to invert
     * @return the inverse element
     * @throws NullPointerException     if element is null
     * @throws IllegalArgumentException if element is not in this group
     */
    E inverse(E element);

    /**
     * Tests whether this is an abelian (commutative) group.
     * 
     * @return {@code true} if this group is abelian
     */
    @Override
    boolean isCommutative();
}

