/*
 * JScience Reimagined - Unified Scientific Computing Framework
 * Copyright (c) 2025 Silvere Martin-Michiellot
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.jscience.mathematics.structures.groups;

/**
 * A group is a set with an associative binary operation, an identity element,
 * and inverse elements.
 * <p>
 * Groups are fundamental in mathematics, appearing in geometry, number theory,
 * physics (symmetries), and many other areas.
 * </p>
 * 
 * <h2>Mathematical Definition</h2>
 * <p>
 * A group (G, ∗) must satisfy:
 * <ol>
 * <li><strong>Closure</strong>: ∀ a, b ∈ G: a ∗ b ∈ G</li>
 * <li><strong>Associativity</strong>: ∀ a, b, c ∈ G: (a ∗ b) ∗ c = a ∗ (b ∗
 * c)</li>
 * <li><strong>Identity</strong>: ∃ e ∈ G such that ∀ a ∈ G: e ∗ a = a ∗ e =
 * a</li>
 * <li><strong>Inverse</strong>: ∀ a ∈ G, ∃ a⁻¹ ∈ G such that: a ∗ a⁻¹ = a⁻¹ ∗ a
 * = e</li>
 * </ol>
 * </p>
 * 
 * <h2>Examples</h2>
 * <ul>
 * <li>(ℤ, +) - Integers with addition</li>
 * <li>(ℚ\{0}, ×) - Non-zero rationals with multiplication</li>
 * <li>(S₃, ∘) - Symmetric group (permutations of 3 elements)</li>
 * <li>(ℝⁿ, +) - Real vectors with addition</li>
 * </ul>
 * 
 * <h2>Special Cases</h2>
 * <ul>
 * <li><strong>Abelian Group</strong>: Commutative (a ∗ b = b ∗ a)</li>
 * <li><strong>Cyclic Group</strong>: Generated by single element</li>
 * <li><strong>Simple Group</strong>: No non-trivial normal subgroups</li>
 * </ul>
 * 
 * <h2>Usage</h2>
 * 
 * <pre>{@code
 * // Integer addition group
 * Group<Integer> integers = IntegerAdditionGroup.getInstance();
 * 
 * Integer a = 5;
 * Integer b = 3;
 * Integer sum = integers.operate(a, b); // 8
 * Integer identity = integers.identity(); // 0
 * Integer negA = integers.inverse(a); // -5
 * Integer check = integers.operate(a, negA); // 0 (identity)
 * }</pre>
 * 
 * @param <E> the type of elements in this group
 * 
 * @author Silvere Martin-Michiellot
 * @author Gemini AI (Google DeepMind)
 * @version 1.0
 * @since 1.0
 * 
 * @see AbelianGroup
 * @see Ring
 * @see Field
 */
public interface Group<E> extends Monoid<E> {

    /**
     * Returns the inverse of the given element.
     * <p>
     * For element a, returns a⁻¹ such that: a ∗ a⁻¹ = a⁻¹ ∗ a = e (identity).
     * </p>
     * 
     * @param element the element to invert
     * @return the inverse element
     * @throws NullPointerException     if element is null
     * @throws IllegalArgumentException if element is not in this group
     */
    E inverse(E element);

    /**
     * Tests whether this is an abelian (commutative) group.
     * 
     * @return {@code true} if this group is abelian
     */
    @Override
    boolean isCommutative();
}
