/**
 * JEP - Java Expression Parser JEP is a Java package for parsing and
 * evaluating mathematical expressions. It currently supports user defined
 * variables, constant, and functions. A number of common mathematical
 * functions and constants are included. Author: Nathan Funk Copyright (C)
 * 2000 Nathan Funk JEP is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at your
 * option) any later version. JEP is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
 * Public License for more details. You should have received a copy of the GNU
 * General Public License along with JEP; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/* Generated By:JJTree: Do not edit this line. ASTFunNode.java */
package org.jscience.ml.sbml.jep;

import org.jscience.ml.sbml.jep.function.PostfixMathCommandI;


/**
 * Function Node
 */
public class ASTFunNode extends SimpleNode {
    /** The function class used to evaluate the node */
    private PostfixMathCommandI pfmc;

    /** Name of the function */
    private String name;

/**
     * Creates a new ASTFunNode
     *
     * @param id DOCUMENT ME!
     */
    public ASTFunNode(int id) {
        super(id);
    }

/**
     * Creates a new ASTFunNode
     *
     * @param p  DOCUMENT ME!
     * @param id DOCUMENT ME!
     */
    public ASTFunNode(Parser p, int id) {
        super(p, id);
    }

    /**
     * Returns the name of the node (operator symbol or function name).
     *
     * @return DOCUMENT ME!
     */
    public String getName() {
        return name;
    }

    /**
     * Returns the math command class associated with this node.
     *
     * @return DOCUMENT ME!
     */
    public PostfixMathCommandI getPFMC() {
        return pfmc;
    }

    /**
     * Accept the visitor.
     *
     * @param visitor DOCUMENT ME!
     * @param data DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Object jjtAccept(ParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    /**
     * Sets the function for a node. A name and function class must be
     * specified.
     *
     * @param name_in DOCUMENT ME!
     * @param pfmc_in DOCUMENT ME!
     */
    public void setFunction(String name_in, PostfixMathCommandI pfmc_in) {
        name = name_in;
        pfmc = pfmc_in;
    }

    /**
     * Returns a string containing the function name.
     *
     * @return DOCUMENT ME!
     */
    public String toString() {
        return name;
    }
}
