/* Generated By:JJTree: Do not edit this line. ASTIfThen.java */
package org.jscience.ml.sbml.jep;

/**
 * DOCUMENT ME!
 *
 * @author $author$
 * @version $Revision: 1.3 $
 */
public class ASTIfThen extends SimpleNode {
/**
     * Creates a new ASTIfThen object.
     *
     * @param id DOCUMENT ME!
     */
    public ASTIfThen(int id) {
        super(id);
    }

/**
     * Creates a new ASTIfThen object.
     *
     * @param p  DOCUMENT ME!
     * @param id DOCUMENT ME!
     */
    public ASTIfThen(Parser p, int id) {
        super(p, id);
    }

    /**
     * Accept the visitor.
     *
     * @param visitor DOCUMENT ME!
     * @param data DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Object jjtAccept(ParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
