/*
 * JScience - Java(TM) Tools and Libraries for the Advancement of Sciences.
 * Copyright (C) 2025-2026 - Silvere Martin-Michiellot and Gemini AI (Google DeepMind)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/* Generated By:JJTree: Do not edit this line. ASTVarNode.java */
package org.jscience.ml.sbml.jep;

/**
 * Variable Node
 */
public class ASTVarNode extends SimpleNode {
    /** DOCUMENT ME! */
    private String varName;

/**
     * Creates a new ASTVarNode object.
     *
     * @param id DOCUMENT ME!
     */
    public ASTVarNode(int id) {
        super(id);
        varName = "";
    }

/**
     * Creates a new ASTVarNode object.
     *
     * @param p  DOCUMENT ME!
     * @param id DOCUMENT ME!
     */
    public ASTVarNode(Parser p, int id) {
        super(p, id);
    }

    /**
     * Returns the name of the variable.
     *
     * @return DOCUMENT ME!
     */
    public String getName() {
        return varName;
    }

    /**
     * Accept the visitor.
     *
     * @param visitor DOCUMENT ME!
     * @param data DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Object jjtAccept(ParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    /**
     * Sets the name of the variable.
     *
     * @param varName_in DOCUMENT ME!
     */
    public void setName(String varName_in) {
        varName = varName_in;
    }

    /**
     * Creates a string containing the variable's name
     *
     * @return DOCUMENT ME!
     */
    public String toString() {
        return varName;
    }
}
