/**
 * JEP - Java Expression Parser JEP is a Java package for parsing and
 * evaluating mathematical expressions. It currently supports user defined
 * variables, constant, and functions. A number of common mathematical
 * functions and constants are included. Author: Nathan Funk Copyright (C)
 * 2000 Nathan Funk JEP is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at your
 * option) any later version. JEP is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
 * Public License for more details. You should have received a copy of the GNU
 * General Public License along with JEP; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/* Generated By:JJTree: Do not edit this line. Node.java */
/* All AST nodes must implement this interface.  It provides basic
   machinery for constructing the parent and child relationships
   between nodes. */
package org.jscience.ml.sbml.jep;

/**
 * DOCUMENT ME!
 *
 * @author $author$
 * @version $Revision: 1.3 $
 */
public interface Node {
    /**
     * Accept the visitor.
     *
     * @param visitor DOCUMENT ME!
     * @param data DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    Object jjtAccept(ParserVisitor visitor, Object data);

    /**
     * This method tells the node to add its argument to the node's
     * list of children.
     *
     * @param n DOCUMENT ME!
     * @param i DOCUMENT ME!
     */
    void jjtAddChild(Node n, int i);

    /**
     * This method is called after all the child nodes have been added.
     */
    void jjtClose();

    /**
     * This method returns a child node.  The children are numbered
     * from zero, left to right.
     *
     * @param i DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    Node jjtGetChild(int i);

    /**
     * Return the number of children the node has.
     *
     * @return DOCUMENT ME!
     */
    int jjtGetNumChildren();

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    Node jjtGetParent();

    /**
     * This method is called after the node has been made the current
     * node.  It indicates that child nodes can now be added to it.
     */
    void jjtOpen();

    /**
     * This pair of methods are used to inform the node of its parent.
     *
     * @param n DOCUMENT ME!
     */
    void jjtSetParent(Node n);

/**
     * Push the value of the node on the stack  public void evaluate(Stack
     * stack) throws ParseException;
     */
}
