/*
 * JScience - Java(TM) Tools and Libraries for the Advancement of Sciences.
 * Copyright (C) 2025-2026 - Silvere Martin-Michiellot and Gemini AI (Google DeepMind)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/* Generated By:JJTree: Do not edit this line. Node.java */
/* All AST nodes must implement this interface.  It provides basic
   machinery for constructing the parent and child relationships
   between nodes. */
package org.jscience.ml.sbml.jep;

/**
 * DOCUMENT ME!
 *
 * @author $author$
 * @version $Revision: 1.3 $
 */
public interface Node {
    /**
     * Accept the visitor.
     *
     * @param visitor DOCUMENT ME!
     * @param data DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    Object jjtAccept(ParserVisitor visitor, Object data);

    /**
     * This method tells the node to add its argument to the node's
     * list of children.
     *
     * @param n DOCUMENT ME!
     * @param i DOCUMENT ME!
     */
    void jjtAddChild(Node n, int i);

    /**
     * This method is called after all the child nodes have been added.
     */
    void jjtClose();

    /**
     * This method returns a child node.  The children are numbered
     * from zero, left to right.
     *
     * @param i DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    Node jjtGetChild(int i);

    /**
     * Return the number of children the node has.
     *
     * @return DOCUMENT ME!
     */
    int jjtGetNumChildren();

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    Node jjtGetParent();

    /**
     * This method is called after the node has been made the current
     * node.  It indicates that child nodes can now be added to it.
     */
    void jjtOpen();

    /**
     * This pair of methods are used to inform the node of its parent.
     *
     * @param n DOCUMENT ME!
     */
    void jjtSetParent(Node n);

/**
     * Push the value of the node on the stack  public void evaluate(Stack
     * stack) throws ParseException;
     */
}
