/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package org.jscience.ml.sbml.jep;

/**
 * DOCUMENT ME!
 *
 * @author $author$
 * @version $Revision: 1.3 $
 */
public interface ParserConstants {
    /** DOCUMENT ME! */
    String[] tokenImage = {
            "<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"",
            "<INTEGER_LITERAL>", "<DECIMAL_LITERAL>", "<FLOATING_POINT_LITERAL>",
            "<EXPONENT>", "\"\\\\\"", "\">\"", "\"<\"", "\"=\"", "\"<=\"",
            "\">=\"", "\"!=\"", "\"AND\"", "\"OR\"", "\"XOR\"", "\"NOT\"",
            "\"+\"", "\"-\"", "\"*\"", "\"/\"", "\"^\"", "\"if\"", "\"elseif\"",
            "\"else\"", "\"then\"", "\"true\"", "\"false\"", "<IDENTIFIER>",
            "<LETTER>", "<DIGIT>", "<ESC>", "\"(\"", "\")\"", "\",\"",
        };

    /** DOCUMENT ME! */
    int AND = 16;

    /** DOCUMENT ME! */
    int DECIMAL_LITERAL = 6;

    /** DOCUMENT ME! */
    int DEFAULT = 0;

    /** DOCUMENT ME! */
    int DIGIT = 33;

    /** DOCUMENT ME! */
    int DIV = 23;

    /** DOCUMENT ME! */
    int ELSE = 27;

    /** DOCUMENT ME! */
    int ELSEIF = 26;

    /** DOCUMENT ME! */
    int EOF = 0;

    /** DOCUMENT ME! */
    int EQ = 12;

    /** DOCUMENT ME! */
    int ESC = 34;

    /** DOCUMENT ME! */
    int ESCAP = 9;

    /** DOCUMENT ME! */
    int EXPONENT = 8;

    /** DOCUMENT ME! */
    int FALSE = 30;

    /** DOCUMENT ME! */
    int FLOATING_POINT_LITERAL = 7;

    /** DOCUMENT ME! */
    int GE = 14;

    /** DOCUMENT ME! */
    int GT = 10;

    /** DOCUMENT ME! */
    int IDENTIFIER = 31;

    /** DOCUMENT ME! */
    int IF = 25;

    /** DOCUMENT ME! */
    int INTEGER_LITERAL = 5;

    /** DOCUMENT ME! */
    int LE = 13;

    /** DOCUMENT ME! */
    int LETTER = 32;

    /** DOCUMENT ME! */
    int LT = 11;

    /** DOCUMENT ME! */
    int MINUS = 21;

    /** DOCUMENT ME! */
    int MUL = 22;

    /** DOCUMENT ME! */
    int NE = 15;

    /** DOCUMENT ME! */
    int NOT = 19;

    /** DOCUMENT ME! */
    int OR = 17;

    /** DOCUMENT ME! */
    int PLUS = 20;

    /** DOCUMENT ME! */
    int POWER = 24;

    /** DOCUMENT ME! */
    int THEN = 28;

    /** DOCUMENT ME! */
    int TRUE = 29;

    /** DOCUMENT ME! */
    int XOR = 18;
}
