/* Generated By:JJTree: Do not edit this line. ParserTreeConstants.java */
package org.jscience.ml.sbml.jep;

/**
 * DOCUMENT ME!
 *
 * @author $author$
 * @version $Revision: 1.3 $
 */
public interface ParserTreeConstants {
    /** DOCUMENT ME! */
    String[] jjtNodeName = {
            "Start", "void", "FunNode", "VarNode", "IfThen", "ElseIfThen",
            "Else", "Piecewise", "Constant",
        };

    /** DOCUMENT ME! */
    int JJTCONSTANT = 8;

    /** DOCUMENT ME! */
    int JJTELSE = 6;

    /** DOCUMENT ME! */
    int JJTELSEIFTHEN = 5;

    /** DOCUMENT ME! */
    int JJTFUNNODE = 2;

    /** DOCUMENT ME! */
    int JJTIFTHEN = 4;

    /** DOCUMENT ME! */
    int JJTPIECEWISE = 7;

    /** DOCUMENT ME! */
    int JJTSTART = 0;

    /** DOCUMENT ME! */
    int JJTVARNODE = 3;

    /** DOCUMENT ME! */
    int JJTVOID = 1;
}
