/* Generated By:JJTree: Do not edit this line. ParserVisitor.java */
package org.jscience.ml.sbml.jep;

/**
 * DOCUMENT ME!
 *
 * @author $author$
 * @version $Revision: 1.3 $
 */
public interface ParserVisitor {
    /**
     * DOCUMENT ME!
     *
     * @param node DOCUMENT ME!
     * @param data DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    Object visit(SimpleNode node, Object data);

    /**
     * DOCUMENT ME!
     *
     * @param node DOCUMENT ME!
     * @param data DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    Object visit(ASTStart node, Object data);

    /**
     * DOCUMENT ME!
     *
     * @param node DOCUMENT ME!
     * @param data DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    Object visit(ASTFunNode node, Object data);

    /**
     * DOCUMENT ME!
     *
     * @param node DOCUMENT ME!
     * @param data DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    Object visit(ASTVarNode node, Object data);

    /**
     * DOCUMENT ME!
     *
     * @param node DOCUMENT ME!
     * @param data DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    Object visit(ASTIfThen node, Object data);

    /**
     * DOCUMENT ME!
     *
     * @param node DOCUMENT ME!
     * @param data DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    Object visit(ASTElseIfThen node, Object data);

    /**
     * DOCUMENT ME!
     *
     * @param node DOCUMENT ME!
     * @param data DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    Object visit(ASTElse node, Object data);

    /**
     * DOCUMENT ME!
     *
     * @param node DOCUMENT ME!
     * @param data DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    Object visit(ASTPiecewise node, Object data);

    /**
     * DOCUMENT ME!
     *
     * @param node DOCUMENT ME!
     * @param data DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    Object visit(ASTConstant node, Object data);
}
