/*
 * JScience - Java(TM) Tools and Libraries for the Advancement of Sciences.
 * Copyright (C) 2025-2026 - Silvere Martin-Michiellot and Gemini AI (Google DeepMind)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/* Generated By:JJTree: Do not edit this line. ParserTreeConstants.java */
package org.jscience.ml.sbml.jep;

/**
 * DOCUMENT ME!
 *
 * @author $author$
 * @version $Revision: 1.3 $
 */
public interface ParserTreeConstants {
    /** DOCUMENT ME! */
    String[] jjtNodeName = {
            "Start", "void", "FunNode", "VarNode", "IfThen", "ElseIfThen",
            "Else", "Piecewise", "Constant",
        };

    /** DOCUMENT ME! */
    int JJTCONSTANT = 8;

    /** DOCUMENT ME! */
    int JJTELSE = 6;

    /** DOCUMENT ME! */
    int JJTELSEIFTHEN = 5;

    /** DOCUMENT ME! */
    int JJTFUNNODE = 2;

    /** DOCUMENT ME! */
    int JJTIFTHEN = 4;

    /** DOCUMENT ME! */
    int JJTPIECEWISE = 7;

    /** DOCUMENT ME! */
    int JJTSTART = 0;

    /** DOCUMENT ME! */
    int JJTVARNODE = 3;

    /** DOCUMENT ME! */
    int JJTVOID = 1;
}
