/*
 * $Id: PhrasebookException.java,v 1.2 2007-10-21 17:46:59 virtualcall Exp $
 *
 * Copyright (c) 2001-2004, RIACA, Technische Universiteit Eindhoven (TU/e).
 * All Rights Reserved.
 *
 * ---------------------------------------------------------------------------
 *
 *  The contents of this file are subject to the RIACA Public License
 *  Version 1.0 (the "License"). You may not use this file except in
 *  compliance with the License. A copy of the License is available at
 *  http://www.riaca.win.tue.nl/
 *
 *  Alternatively, the contents of this file may be used under the terms
 *  of the GNU Lesser General Public license (the "LGPL license"), in which
 *  case the provisions of the LGPL license are applicable instead of those
 *  above. A copy of the LGPL license is available at http://www.gnu.org/
 *
 *  The Original Code is ROML -- the RIACA OpenMath Library. The Initial
 *  Developer of the Original Code is Manfred N. Riem.  Portions created
 *  by Manfred N. Riem are Copyright (c) 2001. All Rights Reserved.
 *
 *  Contributor(s):
 *
 *      Ernesto Reinaldo Barreiro, Arjeh M. Cohen, Hans Cuypers, Hans Sterk,
 *      Olga Caprotti
 *
 * ---------------------------------------------------------------------------
 */
package org.jscience.ml.openmath.phrasebook;

/**
 * An exception generated by the phrasebook.
 * <p/>
 * <p></p>
 *
 * @author Manfred Riem
 * @version $Version$
 */
public class PhrasebookException extends Exception {
    /**
     * Constructor.
     * <p/>
     * <p></p>
     */
    public PhrasebookException() {
        super();
    }

    /**
     * Constructor.
     * <p/>
     * <p></p>
     *
     * @param fMessage the message associated with the exception.
     */
    public PhrasebookException(String fMessage) {
        super(fMessage);
    }
}
