/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_jscience_net_ntp_LocalTimeManager */

#ifndef _Included_org_jscience_net_ntp_LocalTimeManager
#define _Included_org_jscience_net_ntp_LocalTimeManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jscience_net_ntp_LocalTimeManager
 * Method:    nativeSetTime
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_jscience_net_ntp_LocalTimeManager_nativeSetTime
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
