/*
 * JScience - Java(TM) Tools and Libraries for the Advancement of Sciences.
 * Copyright (C) 2025-2026 - Silvere Martin-Michiellot and Gemini AI (Google DeepMind)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.jscience.biology.loaders;

import org.jscience.biology.Protein;
import org.jscience.chemistry.Atom;
import org.jscience.io.AbstractResourceWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Locale;

/**
 * Writer for PDB files.
 */
public class PDBWriter extends AbstractResourceWriter<Protein> {

    @Override
    public String getResourcePath() {
        // Should ideally be configurable or output directory
        return "https://files.rcsb.org/download/";
    }

    @Override
    public Class<Protein> getResourceType() {
        return Protein.class;
    }

    @Override
    public void save(Protein protein, String destination) throws Exception {
        try (PrintWriter writer = new PrintWriter(new FileWriter(new File(destination)))) {
            writer.println("REMARK   GENERATED BY JSCIENCE");
            writer.printf(Locale.US, "HEADER    %-40s%11s   %4s\n", protein.getName(), "", protein.getPdbId());

            int atomSerial = 1;
            for (Protein.Chain chain : protein.getChains()) {
                for (Protein.Residue residue : chain.getResidues()) {
                    for (Atom atom : residue.getAtoms()) {
                        // PDB ATOM format:
                        // 1-6 ATOM
                        // 7-11 Serial
                        // 13-16 Name
                        // 17 Residue Name
                        // 22 Chain ID
                        // 23-26 Res Num
                        // 31-38 X
                        // 39-46 Y
                        // 47-54 Z
                        writer.printf(Locale.US,
                                "ATOM  %5d %-4s %3s %1s%4d    %8.3f%8.3f%8.3f  1.00  0.00          %2s\n",
                                atomSerial % 100000,
                                atom.getElement().getSymbol(), // Simplified name
                                residue.getName(),
                                chain.getChainId(),
                                residue.getSequenceNumber(),
                                atom.getX(),
                                atom.getY(),
                                atom.getZ(),
                                atom.getElement().getSymbol());
                        atomSerial++;
                    }
                }
            }
            writer.println("END");
        }
    }
}
