/*
 * XmlParser.java
 *
 * Created on Jan 13, 2003, 1:22 AM
 *
 * Copyright (C) 2003 Oezguer Demir <oeze@coli.uni-sb.de>,
 *                    Vaclav Nemcik <vicky@coli.uni-sb.de>,
 *                    Hajo Keffer <hajokeffer@coli.uni-sb.de>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

package org.jscience.ml.tigerxml.core;

import org.jscience.ml.tigerxml.tools.GeneralTools;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;
import org.xml.sax.SAXParseException;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;

/**
 * Provides static XML parsing functionality.
 *
 * @author <a href="mailto:oeze@coli.uni-sb.de">Oezguer Demir</a>
 * @author <a href="mailto:vicky@coli.uni-sb.de">Vaclav Nemcik</a>
 * @author <a href="mailto:hajokeffer@coli.uni-sb.de">Hajo Keffer</a>
 * @version 1.84
 *          $Id: XmlParser.java,v 1.2 2007-10-21 17:47:08 virtualcall Exp $
 */
public class XmlParser {

    /**
     * If this flag is set, the document will be parsed building a DOM tree,
     * if unset, the document will be parsed using SAX.
     */
    private boolean dom = true;

    /**
     * The name of the XML file to be parsed
     */
    private String xmlFileName;

    /**
     * The first line in the XML corpus file. Ex: '<?xml version="1.0" ...'
     */
    private final String xmlDeclaration =
            "<?xml version=\"1.0\" standalone=\"yes\">";

    /**
     * The higher this value the more process and debug information will
     * written to stderr.
     */
    private int verbosity = 0;

    public XmlParser(String xmlFileName) {
        init(xmlFileName);
    }

    public XmlParser(String xmlFileName, int verbosity) {
        this.verbosity = verbosity;
        init(xmlFileName);
    }

    private void init(String xmlFileName) {
        if ((setXmlFileName(xmlFileName)) && (this.verbosity > 2)) {
            System.err.println("org.jscience.ml.tigerxml.core.XmlParser: Initialized, XML Corpus: "
                    + xmlFileName + ".");
        }
    }

    /**
     * Parses the a given XML corpus file.
     *
     * @return The root element of the DOM built from this instances XML file.
     */
    public Element getDOMRootElement() {
        if (this.verbosity > 0) {
            System.err.println("org.jscience.ml.tigerxml.core.XmlParser: Parsing "
                    + this.xmlFileName + " and building DOM tree ...");
        }
        long time = System.currentTimeMillis();
        Document doc = null;
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();

        try {
            DocumentBuilder builder = factory.newDocumentBuilder();
            if (this.verbosity > 3) {
                System.err.println("org.jscience.ml.tigerxml.core.XmlParser: Using XML parser of "
                        + builder.getClass());
            }
            doc = builder.parse(new File(this.xmlFileName));
            // Admittedly, the following is not very nice.
            // But after hours of browsing the Java XML
            // documentation, I still see no other
            // possibility of getting the XML prolog.
            BufferedReader in = new BufferedReader(new FileReader(this.xmlFileName));
            ////FOOxmlProlog = in.readLine();
        } catch (java.io.IOException ex) {
            ex.printStackTrace();
            System.err.println("org.jscience.ml.tigerxml.core.XmlParser: Could not open "
                    + this.xmlFileName
                    + ". Exiting.");
            System.exit(-1);
        } catch (SAXParseException spe) {
            // Error generated by the parser
            if (this.verbosity > 0) {
                System.err.println
                        ("\n** Parsing error"
                                + ", line " +
                                spe.getLineNumber()
                                + ", column " +
                                spe.getColumnNumber() +
                                ", uri " +
                                spe.getSystemId());
                System.err.println("   "
                        + spe.getMessage());
            }
        } catch (SAXException sxe) {
            Exception x = sxe;
            if (sxe.getException() != null) {
                x = sxe.getException();
            }
            x.printStackTrace();
        } catch (ParserConfigurationException pce) {
            pce.printStackTrace();
        }
        NodeList currentNodeList =
                doc.getElementsByTagName("corpus"); //corpus element list
        Element rootElement =
                (Element) currentNodeList.item(0); //corpus element
        if (this.verbosity > 3) {
            time = System.currentTimeMillis() - time;
            System.err.println("org.jscience.ml.tigerxml.core.XmlParser: Parsing XML consumed: " +
                    GeneralTools.timeConvert(time));
        }
        return rootElement;
    } // parseXMLcorp()

    public String getXmlFileName() {
        return this.xmlFileName;
    }

    /**
     * Sets the XML file to be parsed.
     *
     * @param xmlFileName
     * @return <code>True</code> if the file is readable,
     *         <code>false</code> if not.
     */
    public boolean setXmlFileName(String xmlFileName) {
        File test = new File(xmlFileName);
        if (test.canRead()) {
            this.xmlFileName = xmlFileName;
            test = null;
            return true;
        } else {
            test = null;
            if (this.verbosity > 0) {
                System.err.println(this.getClass() + ": Warning: Could not open "
                        + xmlFileName
                        + "for reading!");
            }
            return false;
        }
    }

    /**
     * Gets the currently set level of verbosity of this instance. The higher
     * the value the more information is written to stderr.
     *
     * @return The level of verbosity.
     */
    public int getVerbosity() {
        return this.verbosity;
    }

    /**
     * Sets the currently set level of verbosity of this instance. The higher
     * the value the more information is written to stderr.
     *
     * @param verbosity The level of verbosity.
     */
    public void setVerbosity(int verbosity) {
        this.verbosity = verbosity;
    }

    public void useDOM() {
        this.dom = true;
        if (this.verbosity > 2) {
            System.err.println("org.jscience.ml.tigerxml.core.XmlParser: Parser set to 'DOM'");
        }
    }

    public void useSAX() {
        this.dom = false;
        if (this.verbosity > 2) {
            System.err.println("org.jscience.ml.tigerxml.core.XmlParser: Parser set to 'SAX'");
        }
    }

} // class
