/*
 * JScience - Java(TM) Tools and Libraries for the Advancement of Sciences.
 * Copyright (C) 2025 - Silvere Martin-Michiellot (silvere.martin@gmail.com)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: linear_algebra_service.proto

// Protobuf Java Version: 3.25.1
package org.jscience.distributed.grpc;

public final class LinearAlgebraServiceProto {
  private LinearAlgebraServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jscience_computing_remote_MatrixRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_jscience_computing_remote_MatrixRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jscience_computing_remote_MatrixResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_jscience_computing_remote_MatrixResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jscience_computing_remote_MatrixData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_jscience_computing_remote_MatrixData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034linear_algebra_service.proto\022\035org.jsci" +
      "ence.computing.remote\"\211\001\n\rMatrixRequest\022" +
      ";\n\010matrix_a\030\001 \001(\0132).org.jscience.computi" +
      "ng.remote.MatrixData\022;\n\010matrix_b\030\002 \001(\0132)" +
      ".org.jscience.computing.remote.MatrixDat" +
      "a\"K\n\016MatrixResponse\0229\n\006result\030\001 \001(\0132).or" +
      "g.jscience.computing.remote.MatrixData\"6" +
      "\n\nMatrixData\022\014\n\004rows\030\001 \001(\005\022\014\n\004cols\030\002 \001(\005" +
      "\022\014\n\004data\030\003 \003(\0012\200\001\n\rMatrixService\022o\n\016Matr" +
      "ixMultiply\022,.org.jscience.computing.remo" +
      "te.MatrixRequest\032-.org.jscience.computin" +
      "g.remote.MatrixResponse\"\000BA\n\"org.jscienc" +
      "e.computing.remote.grpcB\031LinearAlgebraSe" +
      "rviceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_jscience_computing_remote_MatrixRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_jscience_computing_remote_MatrixRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_jscience_computing_remote_MatrixRequest_descriptor,
        new java.lang.String[] { "MatrixA", "MatrixB", });
    internal_static_org_jscience_computing_remote_MatrixResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_jscience_computing_remote_MatrixResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_jscience_computing_remote_MatrixResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_org_jscience_computing_remote_MatrixData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_jscience_computing_remote_MatrixData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_jscience_computing_remote_MatrixData_descriptor,
        new java.lang.String[] { "Rows", "Cols", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
