// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: linear_algebra_service.proto

// Protobuf Java Version: 3.25.1
package org.jscience.distributed.grpc;

/**
 * Protobuf type {@code org.jscience.computing.remote.MatrixData}
 */
public final class MatrixData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.jscience.computing.remote.MatrixData)
    MatrixDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MatrixData.newBuilder() to construct.
  private MatrixData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MatrixData() {
    data_ = emptyDoubleList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MatrixData();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.jscience.distributed.grpc.LinearAlgebraServiceProto.internal_static_org_jscience_computing_remote_MatrixData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.jscience.distributed.grpc.LinearAlgebraServiceProto.internal_static_org_jscience_computing_remote_MatrixData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.jscience.distributed.grpc.MatrixData.class, org.jscience.distributed.grpc.MatrixData.Builder.class);
  }

  public static final int ROWS_FIELD_NUMBER = 1;
  private int rows_ = 0;
  /**
   * <code>int32 rows = 1;</code>
   * @return The rows.
   */
  @java.lang.Override
  public int getRows() {
    return rows_;
  }

  public static final int COLS_FIELD_NUMBER = 2;
  private int cols_ = 0;
  /**
   * <code>int32 cols = 2;</code>
   * @return The cols.
   */
  @java.lang.Override
  public int getCols() {
    return cols_;
  }

  public static final int DATA_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.DoubleList data_ =
      emptyDoubleList();
  /**
   * <pre>
   * Row-major order
   * </pre>
   *
   * <code>repeated double data = 3;</code>
   * @return A list containing the data.
   */
  @java.lang.Override
  public java.util.List<java.lang.Double>
      getDataList() {
    return data_;
  }
  /**
   * <pre>
   * Row-major order
   * </pre>
   *
   * <code>repeated double data = 3;</code>
   * @return The count of data.
   */
  public int getDataCount() {
    return data_.size();
  }
  /**
   * <pre>
   * Row-major order
   * </pre>
   *
   * <code>repeated double data = 3;</code>
   * @param index The index of the element to return.
   * @return The data at the given index.
   */
  public double getData(int index) {
    return data_.getDouble(index);
  }
  private int dataMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (rows_ != 0) {
      output.writeInt32(1, rows_);
    }
    if (cols_ != 0) {
      output.writeInt32(2, cols_);
    }
    if (getDataList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(dataMemoizedSerializedSize);
    }
    for (int i = 0; i < data_.size(); i++) {
      output.writeDoubleNoTag(data_.getDouble(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (rows_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, rows_);
    }
    if (cols_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, cols_);
    }
    {
      int dataSize = 0;
      dataSize = 8 * getDataList().size();
      size += dataSize;
      if (!getDataList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      dataMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.jscience.distributed.grpc.MatrixData)) {
      return super.equals(obj);
    }
    org.jscience.distributed.grpc.MatrixData other = (org.jscience.distributed.grpc.MatrixData) obj;

    if (getRows()
        != other.getRows()) return false;
    if (getCols()
        != other.getCols()) return false;
    if (!getDataList()
        .equals(other.getDataList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROWS_FIELD_NUMBER;
    hash = (53 * hash) + getRows();
    hash = (37 * hash) + COLS_FIELD_NUMBER;
    hash = (53 * hash) + getCols();
    if (getDataCount() > 0) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getDataList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.jscience.distributed.grpc.MatrixData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jscience.distributed.grpc.MatrixData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jscience.distributed.grpc.MatrixData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jscience.distributed.grpc.MatrixData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jscience.distributed.grpc.MatrixData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jscience.distributed.grpc.MatrixData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jscience.distributed.grpc.MatrixData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.jscience.distributed.grpc.MatrixData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.jscience.distributed.grpc.MatrixData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.jscience.distributed.grpc.MatrixData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.jscience.distributed.grpc.MatrixData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.jscience.distributed.grpc.MatrixData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.jscience.distributed.grpc.MatrixData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.jscience.computing.remote.MatrixData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.jscience.computing.remote.MatrixData)
      org.jscience.distributed.grpc.MatrixDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jscience.distributed.grpc.LinearAlgebraServiceProto.internal_static_org_jscience_computing_remote_MatrixData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jscience.distributed.grpc.LinearAlgebraServiceProto.internal_static_org_jscience_computing_remote_MatrixData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jscience.distributed.grpc.MatrixData.class, org.jscience.distributed.grpc.MatrixData.Builder.class);
    }

    // Construct using org.jscience.distributed.grpc.MatrixData.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      rows_ = 0;
      cols_ = 0;
      data_ = emptyDoubleList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.jscience.distributed.grpc.LinearAlgebraServiceProto.internal_static_org_jscience_computing_remote_MatrixData_descriptor;
    }

    @java.lang.Override
    public org.jscience.distributed.grpc.MatrixData getDefaultInstanceForType() {
      return org.jscience.distributed.grpc.MatrixData.getDefaultInstance();
    }

    @java.lang.Override
    public org.jscience.distributed.grpc.MatrixData build() {
      org.jscience.distributed.grpc.MatrixData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.jscience.distributed.grpc.MatrixData buildPartial() {
      org.jscience.distributed.grpc.MatrixData result = new org.jscience.distributed.grpc.MatrixData(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.jscience.distributed.grpc.MatrixData result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.rows_ = rows_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.cols_ = cols_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        data_.makeImmutable();
        result.data_ = data_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.jscience.distributed.grpc.MatrixData) {
        return mergeFrom((org.jscience.distributed.grpc.MatrixData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.jscience.distributed.grpc.MatrixData other) {
      if (other == org.jscience.distributed.grpc.MatrixData.getDefaultInstance()) return this;
      if (other.getRows() != 0) {
        setRows(other.getRows());
      }
      if (other.getCols() != 0) {
        setCols(other.getCols());
      }
      if (!other.data_.isEmpty()) {
        if (data_.isEmpty()) {
          data_ = other.data_;
          data_.makeImmutable();
          bitField0_ |= 0x00000004;
        } else {
          ensureDataIsMutable();
          data_.addAll(other.data_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              rows_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              cols_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 25: {
              double v = input.readDouble();
              ensureDataIsMutable();
              data_.addDouble(v);
              break;
            } // case 25
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              int alloc = length > 4096 ? 4096 : length;
              ensureDataIsMutable(alloc / 8);
              while (input.getBytesUntilLimit() > 0) {
                data_.addDouble(input.readDouble());
              }
              input.popLimit(limit);
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int rows_ ;
    /**
     * <code>int32 rows = 1;</code>
     * @return The rows.
     */
    @java.lang.Override
    public int getRows() {
      return rows_;
    }
    /**
     * <code>int32 rows = 1;</code>
     * @param value The rows to set.
     * @return This builder for chaining.
     */
    public Builder setRows(int value) {

      rows_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 rows = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRows() {
      bitField0_ = (bitField0_ & ~0x00000001);
      rows_ = 0;
      onChanged();
      return this;
    }

    private int cols_ ;
    /**
     * <code>int32 cols = 2;</code>
     * @return The cols.
     */
    @java.lang.Override
    public int getCols() {
      return cols_;
    }
    /**
     * <code>int32 cols = 2;</code>
     * @param value The cols to set.
     * @return This builder for chaining.
     */
    public Builder setCols(int value) {

      cols_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 cols = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCols() {
      bitField0_ = (bitField0_ & ~0x00000002);
      cols_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.DoubleList data_ = emptyDoubleList();
    private void ensureDataIsMutable() {
      if (!data_.isModifiable()) {
        data_ = makeMutableCopy(data_);
      }
      bitField0_ |= 0x00000004;
    }
    private void ensureDataIsMutable(int capacity) {
      if (!data_.isModifiable()) {
        data_ = makeMutableCopy(data_, capacity);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <pre>
     * Row-major order
     * </pre>
     *
     * <code>repeated double data = 3;</code>
     * @return A list containing the data.
     */
    public java.util.List<java.lang.Double>
        getDataList() {
      data_.makeImmutable();
      return data_;
    }
    /**
     * <pre>
     * Row-major order
     * </pre>
     *
     * <code>repeated double data = 3;</code>
     * @return The count of data.
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <pre>
     * Row-major order
     * </pre>
     *
     * <code>repeated double data = 3;</code>
     * @param index The index of the element to return.
     * @return The data at the given index.
     */
    public double getData(int index) {
      return data_.getDouble(index);
    }
    /**
     * <pre>
     * Row-major order
     * </pre>
     *
     * <code>repeated double data = 3;</code>
     * @param index The index to set the value at.
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(
        int index, double value) {

      ensureDataIsMutable();
      data_.setDouble(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Row-major order
     * </pre>
     *
     * <code>repeated double data = 3;</code>
     * @param value The data to add.
     * @return This builder for chaining.
     */
    public Builder addData(double value) {

      ensureDataIsMutable();
      data_.addDouble(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Row-major order
     * </pre>
     *
     * <code>repeated double data = 3;</code>
     * @param values The data to add.
     * @return This builder for chaining.
     */
    public Builder addAllData(
        java.lang.Iterable<? extends java.lang.Double> values) {
      ensureDataIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, data_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Row-major order
     * </pre>
     *
     * <code>repeated double data = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      data_ = emptyDoubleList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.jscience.computing.remote.MatrixData)
  }

  // @@protoc_insertion_point(class_scope:org.jscience.computing.remote.MatrixData)
  private static final org.jscience.distributed.grpc.MatrixData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.jscience.distributed.grpc.MatrixData();
  }

  public static org.jscience.distributed.grpc.MatrixData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MatrixData>
      PARSER = new com.google.protobuf.AbstractParser<MatrixData>() {
    @java.lang.Override
    public MatrixData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MatrixData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MatrixData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.jscience.distributed.grpc.MatrixData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

