// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: linear_algebra_service.proto

// Protobuf Java Version: 3.25.1
package org.jscience.distributed.grpc;

public interface MatrixRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jscience.computing.remote.MatrixRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.jscience.computing.remote.MatrixData matrix_a = 1;</code>
   * @return Whether the matrixA field is set.
   */
  boolean hasMatrixA();
  /**
   * <code>.org.jscience.computing.remote.MatrixData matrix_a = 1;</code>
   * @return The matrixA.
   */
  org.jscience.distributed.grpc.MatrixData getMatrixA();
  /**
   * <code>.org.jscience.computing.remote.MatrixData matrix_a = 1;</code>
   */
  org.jscience.distributed.grpc.MatrixDataOrBuilder getMatrixAOrBuilder();

  /**
   * <code>.org.jscience.computing.remote.MatrixData matrix_b = 2;</code>
   * @return Whether the matrixB field is set.
   */
  boolean hasMatrixB();
  /**
   * <code>.org.jscience.computing.remote.MatrixData matrix_b = 2;</code>
   * @return The matrixB.
   */
  org.jscience.distributed.grpc.MatrixData getMatrixB();
  /**
   * <code>.org.jscience.computing.remote.MatrixData matrix_b = 2;</code>
   */
  org.jscience.distributed.grpc.MatrixDataOrBuilder getMatrixBOrBuilder();
}
