// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: linear_algebra_service.proto

// Protobuf Java Version: 3.25.1
package org.jscience.distributed.grpc;

/**
 * Protobuf type {@code org.jscience.computing.remote.MatrixRequest}
 */
public final class MatrixRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.jscience.computing.remote.MatrixRequest)
    MatrixRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MatrixRequest.newBuilder() to construct.
  private MatrixRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MatrixRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MatrixRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.jscience.distributed.grpc.LinearAlgebraServiceProto.internal_static_org_jscience_computing_remote_MatrixRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.jscience.distributed.grpc.LinearAlgebraServiceProto.internal_static_org_jscience_computing_remote_MatrixRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.jscience.distributed.grpc.MatrixRequest.class, org.jscience.distributed.grpc.MatrixRequest.Builder.class);
  }

  private int bitField0_;
  public static final int MATRIX_A_FIELD_NUMBER = 1;
  private org.jscience.distributed.grpc.MatrixData matrixA_;
  /**
   * <code>.org.jscience.computing.remote.MatrixData matrix_a = 1;</code>
   * @return Whether the matrixA field is set.
   */
  @java.lang.Override
  public boolean hasMatrixA() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.org.jscience.computing.remote.MatrixData matrix_a = 1;</code>
   * @return The matrixA.
   */
  @java.lang.Override
  public org.jscience.distributed.grpc.MatrixData getMatrixA() {
    return matrixA_ == null ? org.jscience.distributed.grpc.MatrixData.getDefaultInstance() : matrixA_;
  }
  /**
   * <code>.org.jscience.computing.remote.MatrixData matrix_a = 1;</code>
   */
  @java.lang.Override
  public org.jscience.distributed.grpc.MatrixDataOrBuilder getMatrixAOrBuilder() {
    return matrixA_ == null ? org.jscience.distributed.grpc.MatrixData.getDefaultInstance() : matrixA_;
  }

  public static final int MATRIX_B_FIELD_NUMBER = 2;
  private org.jscience.distributed.grpc.MatrixData matrixB_;
  /**
   * <code>.org.jscience.computing.remote.MatrixData matrix_b = 2;</code>
   * @return Whether the matrixB field is set.
   */
  @java.lang.Override
  public boolean hasMatrixB() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.org.jscience.computing.remote.MatrixData matrix_b = 2;</code>
   * @return The matrixB.
   */
  @java.lang.Override
  public org.jscience.distributed.grpc.MatrixData getMatrixB() {
    return matrixB_ == null ? org.jscience.distributed.grpc.MatrixData.getDefaultInstance() : matrixB_;
  }
  /**
   * <code>.org.jscience.computing.remote.MatrixData matrix_b = 2;</code>
   */
  @java.lang.Override
  public org.jscience.distributed.grpc.MatrixDataOrBuilder getMatrixBOrBuilder() {
    return matrixB_ == null ? org.jscience.distributed.grpc.MatrixData.getDefaultInstance() : matrixB_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getMatrixA());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getMatrixB());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMatrixA());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMatrixB());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.jscience.distributed.grpc.MatrixRequest)) {
      return super.equals(obj);
    }
    org.jscience.distributed.grpc.MatrixRequest other = (org.jscience.distributed.grpc.MatrixRequest) obj;

    if (hasMatrixA() != other.hasMatrixA()) return false;
    if (hasMatrixA()) {
      if (!getMatrixA()
          .equals(other.getMatrixA())) return false;
    }
    if (hasMatrixB() != other.hasMatrixB()) return false;
    if (hasMatrixB()) {
      if (!getMatrixB()
          .equals(other.getMatrixB())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMatrixA()) {
      hash = (37 * hash) + MATRIX_A_FIELD_NUMBER;
      hash = (53 * hash) + getMatrixA().hashCode();
    }
    if (hasMatrixB()) {
      hash = (37 * hash) + MATRIX_B_FIELD_NUMBER;
      hash = (53 * hash) + getMatrixB().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.jscience.distributed.grpc.MatrixRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jscience.distributed.grpc.MatrixRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jscience.distributed.grpc.MatrixRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jscience.distributed.grpc.MatrixRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jscience.distributed.grpc.MatrixRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jscience.distributed.grpc.MatrixRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jscience.distributed.grpc.MatrixRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.jscience.distributed.grpc.MatrixRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.jscience.distributed.grpc.MatrixRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.jscience.distributed.grpc.MatrixRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.jscience.distributed.grpc.MatrixRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.jscience.distributed.grpc.MatrixRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.jscience.distributed.grpc.MatrixRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.jscience.computing.remote.MatrixRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.jscience.computing.remote.MatrixRequest)
      org.jscience.distributed.grpc.MatrixRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jscience.distributed.grpc.LinearAlgebraServiceProto.internal_static_org_jscience_computing_remote_MatrixRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jscience.distributed.grpc.LinearAlgebraServiceProto.internal_static_org_jscience_computing_remote_MatrixRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jscience.distributed.grpc.MatrixRequest.class, org.jscience.distributed.grpc.MatrixRequest.Builder.class);
    }

    // Construct using org.jscience.distributed.grpc.MatrixRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMatrixAFieldBuilder();
        getMatrixBFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      matrixA_ = null;
      if (matrixABuilder_ != null) {
        matrixABuilder_.dispose();
        matrixABuilder_ = null;
      }
      matrixB_ = null;
      if (matrixBBuilder_ != null) {
        matrixBBuilder_.dispose();
        matrixBBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.jscience.distributed.grpc.LinearAlgebraServiceProto.internal_static_org_jscience_computing_remote_MatrixRequest_descriptor;
    }

    @java.lang.Override
    public org.jscience.distributed.grpc.MatrixRequest getDefaultInstanceForType() {
      return org.jscience.distributed.grpc.MatrixRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.jscience.distributed.grpc.MatrixRequest build() {
      org.jscience.distributed.grpc.MatrixRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.jscience.distributed.grpc.MatrixRequest buildPartial() {
      org.jscience.distributed.grpc.MatrixRequest result = new org.jscience.distributed.grpc.MatrixRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.jscience.distributed.grpc.MatrixRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.matrixA_ = matrixABuilder_ == null
            ? matrixA_
            : matrixABuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.matrixB_ = matrixBBuilder_ == null
            ? matrixB_
            : matrixBBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.jscience.distributed.grpc.MatrixRequest) {
        return mergeFrom((org.jscience.distributed.grpc.MatrixRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.jscience.distributed.grpc.MatrixRequest other) {
      if (other == org.jscience.distributed.grpc.MatrixRequest.getDefaultInstance()) return this;
      if (other.hasMatrixA()) {
        mergeMatrixA(other.getMatrixA());
      }
      if (other.hasMatrixB()) {
        mergeMatrixB(other.getMatrixB());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getMatrixAFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getMatrixBFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.jscience.distributed.grpc.MatrixData matrixA_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.jscience.distributed.grpc.MatrixData, org.jscience.distributed.grpc.MatrixData.Builder, org.jscience.distributed.grpc.MatrixDataOrBuilder> matrixABuilder_;
    /**
     * <code>.org.jscience.computing.remote.MatrixData matrix_a = 1;</code>
     * @return Whether the matrixA field is set.
     */
    public boolean hasMatrixA() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.org.jscience.computing.remote.MatrixData matrix_a = 1;</code>
     * @return The matrixA.
     */
    public org.jscience.distributed.grpc.MatrixData getMatrixA() {
      if (matrixABuilder_ == null) {
        return matrixA_ == null ? org.jscience.distributed.grpc.MatrixData.getDefaultInstance() : matrixA_;
      } else {
        return matrixABuilder_.getMessage();
      }
    }
    /**
     * <code>.org.jscience.computing.remote.MatrixData matrix_a = 1;</code>
     */
    public Builder setMatrixA(org.jscience.distributed.grpc.MatrixData value) {
      if (matrixABuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        matrixA_ = value;
      } else {
        matrixABuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.org.jscience.computing.remote.MatrixData matrix_a = 1;</code>
     */
    public Builder setMatrixA(
        org.jscience.distributed.grpc.MatrixData.Builder builderForValue) {
      if (matrixABuilder_ == null) {
        matrixA_ = builderForValue.build();
      } else {
        matrixABuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.org.jscience.computing.remote.MatrixData matrix_a = 1;</code>
     */
    public Builder mergeMatrixA(org.jscience.distributed.grpc.MatrixData value) {
      if (matrixABuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          matrixA_ != null &&
          matrixA_ != org.jscience.distributed.grpc.MatrixData.getDefaultInstance()) {
          getMatrixABuilder().mergeFrom(value);
        } else {
          matrixA_ = value;
        }
      } else {
        matrixABuilder_.mergeFrom(value);
      }
      if (matrixA_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.org.jscience.computing.remote.MatrixData matrix_a = 1;</code>
     */
    public Builder clearMatrixA() {
      bitField0_ = (bitField0_ & ~0x00000001);
      matrixA_ = null;
      if (matrixABuilder_ != null) {
        matrixABuilder_.dispose();
        matrixABuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.org.jscience.computing.remote.MatrixData matrix_a = 1;</code>
     */
    public org.jscience.distributed.grpc.MatrixData.Builder getMatrixABuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getMatrixAFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.jscience.computing.remote.MatrixData matrix_a = 1;</code>
     */
    public org.jscience.distributed.grpc.MatrixDataOrBuilder getMatrixAOrBuilder() {
      if (matrixABuilder_ != null) {
        return matrixABuilder_.getMessageOrBuilder();
      } else {
        return matrixA_ == null ?
            org.jscience.distributed.grpc.MatrixData.getDefaultInstance() : matrixA_;
      }
    }
    /**
     * <code>.org.jscience.computing.remote.MatrixData matrix_a = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.jscience.distributed.grpc.MatrixData, org.jscience.distributed.grpc.MatrixData.Builder, org.jscience.distributed.grpc.MatrixDataOrBuilder> 
        getMatrixAFieldBuilder() {
      if (matrixABuilder_ == null) {
        matrixABuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.jscience.distributed.grpc.MatrixData, org.jscience.distributed.grpc.MatrixData.Builder, org.jscience.distributed.grpc.MatrixDataOrBuilder>(
                getMatrixA(),
                getParentForChildren(),
                isClean());
        matrixA_ = null;
      }
      return matrixABuilder_;
    }

    private org.jscience.distributed.grpc.MatrixData matrixB_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.jscience.distributed.grpc.MatrixData, org.jscience.distributed.grpc.MatrixData.Builder, org.jscience.distributed.grpc.MatrixDataOrBuilder> matrixBBuilder_;
    /**
     * <code>.org.jscience.computing.remote.MatrixData matrix_b = 2;</code>
     * @return Whether the matrixB field is set.
     */
    public boolean hasMatrixB() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.org.jscience.computing.remote.MatrixData matrix_b = 2;</code>
     * @return The matrixB.
     */
    public org.jscience.distributed.grpc.MatrixData getMatrixB() {
      if (matrixBBuilder_ == null) {
        return matrixB_ == null ? org.jscience.distributed.grpc.MatrixData.getDefaultInstance() : matrixB_;
      } else {
        return matrixBBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.jscience.computing.remote.MatrixData matrix_b = 2;</code>
     */
    public Builder setMatrixB(org.jscience.distributed.grpc.MatrixData value) {
      if (matrixBBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        matrixB_ = value;
      } else {
        matrixBBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.org.jscience.computing.remote.MatrixData matrix_b = 2;</code>
     */
    public Builder setMatrixB(
        org.jscience.distributed.grpc.MatrixData.Builder builderForValue) {
      if (matrixBBuilder_ == null) {
        matrixB_ = builderForValue.build();
      } else {
        matrixBBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.org.jscience.computing.remote.MatrixData matrix_b = 2;</code>
     */
    public Builder mergeMatrixB(org.jscience.distributed.grpc.MatrixData value) {
      if (matrixBBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          matrixB_ != null &&
          matrixB_ != org.jscience.distributed.grpc.MatrixData.getDefaultInstance()) {
          getMatrixBBuilder().mergeFrom(value);
        } else {
          matrixB_ = value;
        }
      } else {
        matrixBBuilder_.mergeFrom(value);
      }
      if (matrixB_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.org.jscience.computing.remote.MatrixData matrix_b = 2;</code>
     */
    public Builder clearMatrixB() {
      bitField0_ = (bitField0_ & ~0x00000002);
      matrixB_ = null;
      if (matrixBBuilder_ != null) {
        matrixBBuilder_.dispose();
        matrixBBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.org.jscience.computing.remote.MatrixData matrix_b = 2;</code>
     */
    public org.jscience.distributed.grpc.MatrixData.Builder getMatrixBBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getMatrixBFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.jscience.computing.remote.MatrixData matrix_b = 2;</code>
     */
    public org.jscience.distributed.grpc.MatrixDataOrBuilder getMatrixBOrBuilder() {
      if (matrixBBuilder_ != null) {
        return matrixBBuilder_.getMessageOrBuilder();
      } else {
        return matrixB_ == null ?
            org.jscience.distributed.grpc.MatrixData.getDefaultInstance() : matrixB_;
      }
    }
    /**
     * <code>.org.jscience.computing.remote.MatrixData matrix_b = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.jscience.distributed.grpc.MatrixData, org.jscience.distributed.grpc.MatrixData.Builder, org.jscience.distributed.grpc.MatrixDataOrBuilder> 
        getMatrixBFieldBuilder() {
      if (matrixBBuilder_ == null) {
        matrixBBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.jscience.distributed.grpc.MatrixData, org.jscience.distributed.grpc.MatrixData.Builder, org.jscience.distributed.grpc.MatrixDataOrBuilder>(
                getMatrixB(),
                getParentForChildren(),
                isClean());
        matrixB_ = null;
      }
      return matrixBBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.jscience.computing.remote.MatrixRequest)
  }

  // @@protoc_insertion_point(class_scope:org.jscience.computing.remote.MatrixRequest)
  private static final org.jscience.distributed.grpc.MatrixRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.jscience.distributed.grpc.MatrixRequest();
  }

  public static org.jscience.distributed.grpc.MatrixRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MatrixRequest>
      PARSER = new com.google.protobuf.AbstractParser<MatrixRequest>() {
    @java.lang.Override
    public MatrixRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MatrixRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MatrixRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.jscience.distributed.grpc.MatrixRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

