// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: linear_algebra_service.proto

// Protobuf Java Version: 3.25.1
package org.jscience.computing.remote.grpc;

public interface MatrixResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jscience.computing.remote.MatrixResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.jscience.computing.remote.MatrixData result = 1;</code>
   * @return Whether the result field is set.
   */
  boolean hasResult();
  /**
   * <code>.org.jscience.computing.remote.MatrixData result = 1;</code>
   * @return The result.
   */
  org.jscience.computing.remote.grpc.MatrixData getResult();
  /**
   * <code>.org.jscience.computing.remote.MatrixData result = 1;</code>
   */
  org.jscience.computing.remote.grpc.MatrixDataOrBuilder getResultOrBuilder();
}
