// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: linear_algebra_service.proto

// Protobuf Java Version: 3.25.1
package org.jscience.computing.remote.grpc;

public interface MatrixDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jscience.computing.remote.MatrixData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 rows = 1;</code>
   * @return The rows.
   */
  int getRows();

  /**
   * <code>int32 cols = 2;</code>
   * @return The cols.
   */
  int getCols();

  /**
   * <pre>
   * Row-major order
   * </pre>
   *
   * <code>repeated double data = 3;</code>
   * @return A list containing the data.
   */
  java.util.List<java.lang.Double> getDataList();
  /**
   * <pre>
   * Row-major order
   * </pre>
   *
   * <code>repeated double data = 3;</code>
   * @return The count of data.
   */
  int getDataCount();
  /**
   * <pre>
   * Row-major order
   * </pre>
   *
   * <code>repeated double data = 3;</code>
   * @param index The index of the element to return.
   * @return The data at the given index.
   */
  double getData(int index);
}
