@echo off
echo Starting Loader Verification...
call mvn -f ..\pom.xml compile org.codehaus.mojo:exec-maven-plugin:3.1.0:java -pl jscience-killer-apps "-Dexec.mainClass=org.jscience.apps.util.LoaderVerification"
