.SUFFIXES: .c .o

.c.o:
	$(CC) $(CFLAGS) -c $<

all: scimark2 

CC = gcc 
#CFLAGS = -O2 -funroll-loops 
CFLAGS = -O6


LDFLAGS = 

#CC = cc 
#CC = gcc -ansi -Wall
#CFLAGS = -O 
#LDFLAGS = 

OBJS = FFT.o kernel.o Stopwatch.o Random.o SOR.o SparseCompRow.o \
	array.o MonteCarlo.o LU.o 

scimark2 : scimark2.o $(OBJS)
	$(CC) $(CFLAGS) -o scimark2 scimark2.o $(OBJS) $(LDFLAGS) -lm

