package org.jscience.mathematics.wavelet.splines;

import org.jscience.mathematics.wavelet.MultiscaleFunction;


/**
 * This class is meant as an abstract encapsulation for spline objects.
 */
public abstract class Spline extends MultiscaleFunction implements Cloneable {
    /**
     * DOCUMENT ME!
     *
     * @param j DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public abstract int dimension(int j);

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public abstract int dimension();

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Object clone() {
        Spline s = (Spline) super.clone();

        return (s);
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public abstract String toString();

    /**
     * DOCUMENT ME!
     *
     * @param parm1 DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public abstract double[] evaluate(int parm1);

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public abstract int getFilterType();

    /**
     * DOCUMENT ME!
     *
     * @param parm1 DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public abstract boolean equals(Object parm1);

    /**
     * The interpolate method should be return the actual value of the
     * spline on knots. This value would differ in general from the value
     * generated by the Cascades algorithm and got from the method evaluate.
     * This doesn't apply to splines of order -1,0 and 1.
     *
     * @param j DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public abstract double[] interpolate(int j);
}
