/*
 * JScience - Java(TM) Tools and Libraries for the Advancement of Sciences.
 * Copyright (C) 2025-2026 - Silvere Martin-Michiellot and Gemini AI (Google DeepMind)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.jscience.mathematics.wavelet.splines;

import org.jscience.mathematics.wavelet.MultiscaleFunction;


/**
 * This class is meant as an abstract encapsulation for spline objects.
 */
public abstract class Spline extends MultiscaleFunction implements Cloneable {
    /**
     * DOCUMENT ME!
     *
     * @param j DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public abstract int dimension(int j);

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public abstract int dimension();

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public Object clone() {
        Spline s = (Spline) super.clone();

        return (s);
    }

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public abstract String toString();

    /**
     * DOCUMENT ME!
     *
     * @param parm1 DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public abstract double[] evaluate(int parm1);

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public abstract int getFilterType();

    /**
     * DOCUMENT ME!
     *
     * @param parm1 DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public abstract boolean equals(Object parm1);

    /**
     * The interpolate method should be return the actual value of the
     * spline on knots. This value would differ in general from the value
     * generated by the Cascades algorithm and got from the method evaluate.
     * This doesn't apply to splines of order -1,0 and 1.
     *
     * @param j DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public abstract double[] interpolate(int j);
}
