package org.jscience.mathematics.logic.connectors;

import java.io.IOException;

/**
 * Exporter for Metamath.
 * <p>
 * Generates Metamath database (.mm) files.
 * </p>
 * 
 * @author Silvere Martin-Michiellot
 * @author Gemini AI (Google DeepMind)
 * @since 1.0
 */
public class MetamathExporter implements FormalSystemExporter {

    @Override
    public void exportSystem(java.util.Map<String, Object> system, java.io.Writer writer) throws IOException {
        String name = (String) system.getOrDefault("module", "GeneratedModule");
        writer.write("$( Generated by JScience MetamathExporter $)\n");
        writer.write("$( Module: " + name + " $)\n\n");

        writer.write("$c ( ) -> wff class |- $.\n");
        writer.write("$v P Q R $.\n");
        writer.write("wp $f wff P $.\n");
        writer.write("wq $f wff Q $.\n");
        writer.write("wr $f wff R $.\n\n");

        if (system.containsKey("axioms")) {
            @SuppressWarnings("unchecked")
            java.util.Map<String, String> axioms = (java.util.Map<String, String>) system.get("axioms");
            for (java.util.Map.Entry<String, String> entry : axioms.entrySet()) {
                writer.write("$( Axiom: " + entry.getKey() + " $)\n");
                writer.write("ax-" + entry.getKey() + " $a |- " + entry.getValue() + " $.\n");
            }
        }
    }

    @Override
    public String getFileExtension() {
        return ".mm";
    }
}
