/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jscience_linguistics_search_BoyerMooreSunday */

#ifndef _Included_org_jscience_linguistics_search_BoyerMooreSunday
#define _Included_org_jscience_linguistics_search_BoyerMooreSunday
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jscience_linguistics_search_BoyerMooreSunday_CROSSOVER_IBM_1_3
#define org_jscience_linguistics_search_BoyerMooreSunday_CROSSOVER_IBM_1_3 68L
#undef org_jscience_linguistics_search_BoyerMooreSunday_CROSSOVER_SUN_PRE_1_4
#define org_jscience_linguistics_search_BoyerMooreSunday_CROSSOVER_SUN_PRE_1_4 90L
#undef org_jscience_linguistics_search_BoyerMooreSunday_CROSSOVER_SUN_1_4
#define org_jscience_linguistics_search_BoyerMooreSunday_CROSSOVER_SUN_1_4 12L
/* Inaccessible static: useNative */
/* Inaccessible static: crossover */
/* Inaccessible static: activeDispatch */
/*
 * Class:     org_jscience_linguistics_search_BoyerMooreSunday
 * Method:    nativeSearchBytes
 * Signature: ([BII[BLjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_org_jscience_linguistics_search_BoyerMooreSunday_nativeSearchBytes
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
