/*
 * JScience - Java(TM) Tools and Libraries for the Advancement of Sciences.
 * Copyright (C) 2025 - Silvere Martin-Michiellot (silvere.martin@gmail.com)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.jscience.mathematics.geometry.surfaces;

import org.jscience.mathematics.numbers.real.Real;
import org.jscience.mathematics.geometry.PointND;
import org.jscience.mathematics.geometry.ParametricSurface;
import org.jscience.mathematics.linearalgebra.Vector;
import org.jscience.mathematics.linearalgebra.vectors.DenseVector;
import java.util.Arrays;

/**
 * Represents a torus as a parametric surface.
 * <p>
 * A torus is generated by revolving a circle around an axis.
 * Parametrization:
 * S(u,v) = ((R+r*cos(v))*cos(u), (R+r*cos(v))*sin(u), r*sin(v))
 * where:
 * - R is the major radius (distance from center to tube center)
 * - r is the minor radius (tube radius)
 * - u ∈ [0,2π] is the angle around the major circle
 * - v ∈ [0,2π] is the angle around the minor circle
 * </p>
 * * @author Silvere Martin-Michiellot
 * @author Gemini AI (Google DeepMind)
 * @since 1.0
 */
public class Torus implements ParametricSurface {

    private final PointND center;
    private final Real majorRadius; // R
    private final Real minorRadius; // r

    /**
     * Creates a torus.
     * 
     * @param center      the center point (must be 3D)
     * @param majorRadius the major radius (R)
     * @param minorRadius the minor radius (r)
     */
    public Torus(PointND center, Real majorRadius, Real minorRadius) {
        if (center.ambientDimension() != 3) {
            throw new IllegalArgumentException("Torus requires 3D center");
        }
        if (majorRadius.compareTo(Real.ZERO) <= 0) {
            throw new IllegalArgumentException("Major radius must be positive");
        }
        if (minorRadius.compareTo(Real.ZERO) <= 0) {
            throw new IllegalArgumentException("Minor radius must be positive");
        }
        if (minorRadius.compareTo(majorRadius) >= 0) {
            throw new IllegalArgumentException("Minor radius must be less than major radius");
        }

        this.center = center;
        this.majorRadius = majorRadius;
        this.minorRadius = minorRadius;
    }

    @Override
    public PointND at(Real u, Real v) {
        // x = (R + r*cos(v))*cos(u)
        // y = (R + r*cos(v))*sin(u)
        // z = r*sin(v)

        double uVal = u.doubleValue();
        double vVal = v.doubleValue();
        double R = majorRadius.doubleValue();
        double r = minorRadius.doubleValue();

        double cosU = Math.cos(uVal);
        double sinU = Math.sin(uVal);
        double cosV = Math.cos(vVal);
        double sinV = Math.sin(vVal);

        Real x = Real.of((R + r * cosV) * cosU);
        Real y = Real.of((R + r * cosV) * sinU);
        Real z = Real.of(r * sinV);

        Vector<Real> offset = new DenseVector<>(
                Arrays.asList(x, y, z),
                org.jscience.mathematics.sets.Reals.getInstance());

        return new PointND(center.toVector().add(offset));
    }

    @Override
    public Vector<Real> partialU(Real u, Real v, Real h) {
        // Analytical derivative:
        // ∂S/∂u = (-(R+r*cos(v))*sin(u), (R+r*cos(v))*cos(u), 0)

        double uVal = u.doubleValue();
        double vVal = v.doubleValue();
        double R = majorRadius.doubleValue();
        double r = minorRadius.doubleValue();

        double factor = R + r * Math.cos(vVal);

        Real dx = Real.of(-factor * Math.sin(uVal));
        Real dy = Real.of(factor * Math.cos(uVal));
        Real dz = Real.ZERO;

        return new DenseVector<>(
                Arrays.asList(dx, dy, dz),
                org.jscience.mathematics.sets.Reals.getInstance());
    }

    @Override
    public Vector<Real> partialV(Real u, Real v, Real h) {
        // Analytical derivative:
        // ∂S/∂v = (-r*sin(v)*cos(u), -r*sin(v)*sin(u), r*cos(v))

        double uVal = u.doubleValue();
        double vVal = v.doubleValue();
        double r = minorRadius.doubleValue();

        Real dx = Real.of(-r * Math.sin(vVal) * Math.cos(uVal));
        Real dy = Real.of(-r * Math.sin(vVal) * Math.sin(uVal));
        Real dz = Real.of(r * Math.cos(vVal));

        return new DenseVector<>(
                Arrays.asList(dx, dy, dz),
                org.jscience.mathematics.sets.Reals.getInstance());
    }

    @Override
    public Real gaussianCurvature(Real u, Real v, Real h) {
        // Gaussian curvature of torus:
        // K = cos(v) / (r*(R + r*cos(v)))

        double vVal = v.doubleValue();
        double R = majorRadius.doubleValue();
        double r = minorRadius.doubleValue();

        double cosV = Math.cos(vVal);
        double denominator = r * (R + r * cosV);

        return Real.of(cosV / denominator);
    }

    /**
     * Returns the surface area of the torus.
     * 
     * @return 4π²Rr
     */
    public Real surfaceArea() {
        return majorRadius.multiply(minorRadius)
                .multiply(Real.of(4 * Math.PI * Math.PI));
    }

    /**
     * Returns the volume enclosed by the torus.
     * 
     * @return 2π²Rr²
     */
    public Real volume() {
        return majorRadius.multiply(minorRadius).multiply(minorRadius)
                .multiply(Real.of(2 * Math.PI * Math.PI));
    }

    /**
     * Returns the center of the torus.
     * 
     * @return the center point
     */
    public PointND getCenter() {
        return center;
    }

    /**
     * Returns the major radius.
     * 
     * @return the major radius (R)
     */
    public Real getMajorRadius() {
        return majorRadius;
    }

    /**
     * Returns the minor radius.
     * 
     * @return the minor radius (r)
     */
    public Real getMinorRadius() {
        return minorRadius;
    }

    @Override
    public String toString() {
        return "Torus(center=" + center +
                ", majorRadius=" + majorRadius +
                ", minorRadius=" + minorRadius + ")";
    }
}
