/*
 * Program : ADFC�
 * Class : org.jscience.fluids.gui2.ContinuarSimulacionSerializada
 *         JDialog for preguntar if se desea continuar
 *         a simulacion interrumpida.
 * Director : Leo Gonzalez Gutierrez <leo.gonzalez@iit.upco.es>
 * Programacion : Alejandro Rodriguez Gallego <balrog@amena.com>
 * Date  : 30/11/2001
 *
 * This program se distribuye bajo LICENCIA PUBLICA GNU (GPL)
 */
package org.jscience.physics.fluids.dynamics.gui;

/**
 * DOCUMENT ME!
 *
 * @author balrog
 */
public class ContinueSerializedSimulation extends javax.swing.JInternalFrame {
    /** DOCUMENT ME! */
    boolean isToBeContinued;

    /** DOCUMENT ME! */
    boolean isDone = false;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /** DOCUMENT ME! */
    private org.jscience.physics.fluids.dynamics.gui.JTexturedPanel jTexturedPanel1;

    /** DOCUMENT ME! */
    private javax.swing.JLabel jLabel5;

    /** DOCUMENT ME! */
    private javax.swing.JLabel jLabel1;

    /** DOCUMENT ME! */
    private javax.swing.JLabel jLabel2;

    /** DOCUMENT ME! */
    private javax.swing.JLabel jLabel3;

    /** DOCUMENT ME! */
    private javax.swing.JButton jButtonOk;

    /** DOCUMENT ME! */
    private javax.swing.JButton jButtonNo;

/**
     * Creates new form ContinuarSimulacionSerializada
     */
    public ContinueSerializedSimulation() {
        initComponents();
        isDone = false;
    }

    /**
     * This method is called from within the constructor to initialize
     * the form. WARNING: Do NOT modify this code. The content of this method
     * is always regenerated by the Form Editor.
     */
    private void initComponents() { //GEN-BEGIN:initComponents
        jTexturedPanel1 = new org.jscience.physics.fluids.dynamics.gui.JTexturedPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonOk = new javax.swing.JButton();
        jButtonNo = new javax.swing.JButton();

        jTexturedPanel1.setLayout(null);

        jTexturedPanel1.setTextura(
            "/org.jscience.fluids/recursos/fondoMetal.gif");
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass()
                                                      .getResource("/org.jscience.fluids/recursos/salvavidas.gif")));
        jTexturedPanel1.add(jLabel5);
        jLabel5.setBounds(30, 50, 48, 48);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18));
        jLabel1.setText("Continue existing simulation?");
        jTexturedPanel1.add(jLabel1);
        jLabel1.setBounds(100, 20, 286, 24);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel2.setText("The kernel has detected information of a simulation");
        jTexturedPanel1.add(jLabel2);
        jLabel2.setBounds(100, 60, 309, 16);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel3.setText(
            "that is not finished. Do you want to continue with it?");
        jTexturedPanel1.add(jLabel3);
        jLabel3.setBounds(100, 80, 275, 16);

        jButtonOk.setLabel("Yes, continue with detected simulation");
        jButtonOk.setAutoscrolls(true);
        jButtonOk.setOpaque(false);
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonOkActionPerformed(evt);
                }
            });

        jTexturedPanel1.add(jButtonOk);
        jButtonOk.setBounds(100, 120, 106, 26);

        jButtonNo.setText("No, desde the start");
        jButtonNo.setOpaque(false);
        jButtonNo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonNoActionPerformed(evt);
                }
            });

        jTexturedPanel1.add(jButtonNo);
        jButtonNo.setBounds(230, 120, 174, 26);

        getContentPane().add(jTexturedPanel1, java.awt.BorderLayout.CENTER);

        pack();
    } //GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param evt DOCUMENT ME!
     */
    private void jButtonNoActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButtonNoActionPerformed
        // Add your handling code here:
        isToBeContinued = false;
        isDone = true;

        //notifyAll();
        dispose();
    } //GEN-LAST:event_jButtonNoActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param evt DOCUMENT ME!
     */
    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButtonOkActionPerformed
        // Add your handling code here:
        isToBeContinued = true;
        isDone = true;

        //notifyAll();
        dispose();
    } //GEN-LAST:event_jButtonOkActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @return DOCUMENT ME!
     */
    public boolean getRespuestaContinuarSimulacion() {
        while (!isDone)

            try {
                Thread.sleep(100);
            } catch (Exception ex) {
                ex.printStackTrace();
            }

        return isToBeContinued;
    }

    // End of variables declaration//GEN-END:variables
}
