/*
 * JScience - Java(TM) Tools and Libraries for the Advancement of Sciences.
 * Copyright (C) 2025-2026 - Silvere Martin-Michiellot and Gemini AI (Google DeepMind)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.jscience.physics.fluids.dynamics.gui;

/**
 * DOCUMENT ME!
 *
 * @author balrog
 */
public class ErrorFatal extends javax.swing.JDialog {
    // Variables declaration - do not modify//GEN-BEGIN:variables
    /** DOCUMENT ME! */
    private org.jscience.physics.fluids.dynamics.gui.JTexturedPanel jTexturedPanel2;

    /** DOCUMENT ME! */
    private javax.swing.JLabel jLabel1;

    /** DOCUMENT ME! */
    private javax.swing.JLabel jLabelTitulo;

    /** DOCUMENT ME! */
    private javax.swing.JButton jButtonOk;

    /** DOCUMENT ME! */
    private javax.swing.JTextPane jTextPaneDescripcion;

/**
     * Creates new form Error
     *
     * @param parent DOCUMENT ME!
     * @param modal  DOCUMENT ME!
     * @param text   DOCUMENT ME!
     */
    public ErrorFatal(java.awt.Frame parent, boolean modal, String text) {
        super(parent, modal);
        initComponents();

        jTextPaneDescripcion.setText(text);

        pack();

        java.awt.Point p = parent.getLocationOnScreen();
        java.awt.Dimension dP = parent.getSize();
        java.awt.Dimension dM = getSize();

        setLocation(p.x + ((dP.width - dM.width) / 2),
            p.y + ((dP.height - dM.height) / 2));
    }

    /**
     * This method is called from within the constructor to initialize
     * the form. WARNING: Do NOT modify this code. The content of this method
     * is always regenerated by the FormEditor.
     */
    private void initComponents() { //GEN-BEGIN:initComponents
        jTexturedPanel2 = new org.jscience.physics.fluids.dynamics.gui.JTexturedPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonOk = new javax.swing.JButton();
        jTextPaneDescripcion = new javax.swing.JTextPane();

        getContentPane()
            .setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setTitle("Error");
        addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    closeDialog(evt);
                }
            });

        jTexturedPanel2.setLayout(null);

        jTexturedPanel2.setTextura(
            "/org.jscience.fluids/recursos/fondoMetal.gif");
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass()
                                                      .getResource("/org.jscience.fluids/recursos/error.gif")));
        jLabel1.setToolTipText("");
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18));
        jTexturedPanel2.add(jLabel1);
        jLabel1.setBounds(30, 30, 48, 48);

        jLabelTitulo.setText("Error Fatal");
        jLabelTitulo.setForeground(java.awt.Color.red);
        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 18));
        jTexturedPanel2.add(jLabelTitulo);
        jLabelTitulo.setBounds(130, 20, 109, 19);

        jButtonOk.setText("Ok");
        jButtonOk.setOpaque(false);
        jTexturedPanel2.add(jButtonOk);
        jButtonOk.setBounds(430, 150, 53, 23);

        jTextPaneDescripcion.setOpaque(false);
        jTexturedPanel2.add(jTextPaneDescripcion);
        jTextPaneDescripcion.setBounds(130, 50, 370, 90);

        getContentPane()
            .add(jTexturedPanel2,
            new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 190));
    } //GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param evt DOCUMENT ME!
     */
    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButtonOkActionPerformed
        // Add your handling code here:
        setVisible(false);
        dispose();
    } //GEN-LAST:event_jButtonOkActionPerformed

    /**
     * Closes the dialog
     *
     * @param evt DOCUMENT ME!
     */
    private void closeDialog(java.awt.event.WindowEvent evt) { //GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    } //GEN-LAST:event_closeDialog

    // End of variables declaration//GEN-END:variables
}
