/*
 * JScience - Java(TM) Tools and Libraries for the Advancement of Sciences.
 * Copyright (C) 2025-2026 - Silvere Martin-Michiellot and Gemini AI (Google DeepMind)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.jscience.physics.fluids.dynamics.gui;

import org.jscience.physics.fluids.dynamics.KernelADFC;


/**
 * DOCUMENT ME!
 *
 * @author XuGa2000
 */
public class QuitDialog extends javax.swing.JDialog {
    /** DOCUMENT ME! */
    private KernelADFC kernel;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /** DOCUMENT ME! */
    private org.jscience.physics.fluids.dynamics.gui.JTexturedPanel jTexturedPanel1;

    /** DOCUMENT ME! */
    private javax.swing.JLabel jLabelImagen;

    /** DOCUMENT ME! */
    private javax.swing.JLabel jLabel4;

    /** DOCUMENT ME! */
    private javax.swing.JButton jButtonSi;

    /** DOCUMENT ME! */
    private javax.swing.JButton jButtonNo;

    /** DOCUMENT ME! */
    private javax.swing.JLabel jLabel11;

    /** DOCUMENT ME! */
    private javax.swing.JLabel jLabel12;

/**
     * Creates new form QuitDialog
     *
     * @param kadfc  DOCUMENT ME!
     * @param parent DOCUMENT ME!
     * @param modal  DOCUMENT ME!
     */
    public QuitDialog(KernelADFC kadfc, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        kernel = kadfc;

        initComponents();

        java.awt.Point p = parent.getLocationOnScreen();
        java.awt.Dimension dP = parent.getSize();
        java.awt.Dimension dM = getSize();

        setLocation(p.x + ((dP.width - dM.width) / 2),
            p.y + ((dP.height - dM.height) / 2));
    }

    /**
     * This method is called from within the constructor to initialize
     * the form. WARNING: Do NOT modify this code. The content of this method
     * is always regenerated by the Form Editor.
     */
    private void initComponents() { //GEN-BEGIN:initComponents
        jTexturedPanel1 = new org.jscience.physics.fluids.dynamics.gui.JTexturedPanel();
        jLabelImagen = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonSi = new javax.swing.JButton();
        jButtonNo = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        getContentPane()
            .setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setTitle("Confirmation");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    closeDialog(evt);
                }
            });

        jTexturedPanel1.setLayout(null);

        jTexturedPanel1.setTextura(
            "/org.jscience.fluids/recursos/fondoMetal.gif");
        jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass()
                                                           .getResource("/org.jscience.fluids/recursos/advertencia.gif")));
        jLabelImagen.setToolTipText("");
        jLabelImagen.setFont(new java.awt.Font("Dialog", 0, 18));
        jTexturedPanel1.add(jLabelImagen);
        jLabelImagen.setBounds(30, 30, 48, 48);

        jLabel4.setText("Do you really want to quit?");
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18));
        jTexturedPanel1.add(jLabel4);
        jLabel4.setBounds(140, 20, 219, 19);

        jButtonSi.setText("Yes, of course");
        jButtonSi.setOpaque(false);
        jButtonSi.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonSiActionPerformed(evt);
                }
            });

        jTexturedPanel1.add(jButtonSi);
        jButtonSi.setBounds(140, 120, 91, 23);

        jButtonNo.setText("No!");
        jButtonNo.setOpaque(false);
        jButtonNo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonNoActionPerformed(evt);
                }
            });

        jTexturedPanel1.add(jButtonNo);
        jButtonNo.setBounds(280, 120, 63, 23);

        jLabel11.setText("All information not stored will be lost\u00e1");
        jLabel11.setForeground(java.awt.Color.black);
        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12));
        jTexturedPanel1.add(jLabel11);
        jLabel11.setBounds(120, 60, 278, 13);

        jLabel12.setText("and current simulations will be stopped!");
        jLabel12.setForeground(java.awt.Color.black);
        jLabel12.setFont(new java.awt.Font("Dialog", 0, 12));
        jTexturedPanel1.add(jLabel12);
        jLabel12.setBounds(130, 80, 241, 13);

        getContentPane()
            .add(jTexturedPanel1,
            new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 190));

        pack();
    } //GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param evt DOCUMENT ME!
     */
    private void jButtonNoActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButtonNoActionPerformed
        // Add your handling code here:
        closeDialog(null);
    } //GEN-LAST:event_jButtonNoActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param evt DOCUMENT ME!
     */
    private void jButtonSiActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButtonSiActionPerformed
        // Add your handling code here:
        System.exit(0);
    } //GEN-LAST:event_jButtonSiActionPerformed

    /**
     * Closes the dialog
     *
     * @param evt DOCUMENT ME!
     */
    private void closeDialog(java.awt.event.WindowEvent evt) { //GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    } //GEN-LAST:event_closeDialog

    /**
     * DOCUMENT ME!
     *
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        new QuitDialog(null, new javax.swing.JFrame(), true).show();
    }

    // End of variables declaration//GEN-END:variables
}
