/*
 * JScience - Java(TM) Tools and Libraries for the Advancement of Sciences.
 * Copyright (C) 2025-2026 - Silvere Martin-Michiellot and Gemini AI (Google DeepMind)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.jscience.engineering.eventdriven;

import java.util.LinkedList;


/**
 * <p/>
 * Implements a synchronized, two-level priority queue of events to be
 * delivered to entities by the Engine.
 * </p>
 * <p/>
 * <p/>
 * Internal events, i.e. events generated by an entity for delivery to itself
 * to force an immediate state change, take precedence over Normal events
 * (events generated outside the engine or by one entity for delivery to
 * another).
 * </p>
 *
 * @author Pete Ford, May 30, 2005 &copy;Pete Ford &amp; CodeXombie.com 2005
 */

//**********************************************
//
//This package is rebundled after the code from JSpasm
//
// Project Homepage : http://jspasm.sourceforge.net/
// Original Developer : Pete Ford
// Official Domain : CodeXombie.com
//
//**********************************************

final class EventQueue {
    /**
     * <p/>
     * The high-priority internal event list.
     * </p>
     */
    private LinkedList internalQueue;

    /**
     * <p/>
     * The normal-priority event list.
     * </p>
     */
    private LinkedList normalQueue;

    /**
     * <p/>
     * Constructor.
     * </p>
     */
    EventQueue() {
        internalQueue = new LinkedList();
        normalQueue = new LinkedList();
    }

    /**
     * <p/>
     * Removes and returns the next event from the queue. Internal events are
     * always taken first; normal events are selected only when there are no
     * internal events. Aside from this constraint, events are always taken in
     * the same order that they were queued.
     * </p>
     * <p/>
     * <p/>
     * If there are no events of either kind in the queue, the calling thread
     * is blocked until another thread queues an event or an interrupt is
     * received.
     * </p>
     *
     * @return The next event.
     * @throws InterruptedException DOCUMENT ME!
     */
    Event dequeue() throws InterruptedException {
        Event event;

        synchronized (this) {
            while ((internalQueue.isEmpty()) && (normalQueue.isEmpty())) {
                wait();
            }

            if (!internalQueue.isEmpty()) {
                event = (Event) internalQueue.removeFirst();
            } else {
                event = (Event) normalQueue.removeFirst();
            }
        }

        return event;
    }

    /**
     * <p/>
     * Queues an event at normal priority. If the engine thread is blocked
     * waiting for an event, it will be notified and unblocked.
     * </p>
     *
     * @param event The event to queue.
     */
    void queueNormal(Event event) {
        synchronized (this) {
            normalQueue.addLast(event);
            notifyAll();
        }
    }

    /**
     * <p/>
     * Queues an event at high priority. If the engine thread is blocked
     * waiting for an event, it will be notified and unblocked.
     * </p>
     *
     * @param event The event to queue.
     */
    void queueInternal(Event event) {
        synchronized (this) {
            internalQueue.addLast(event);
            notifyAll();
        }
    }
}
