package org.jscience.engineering.eventdriven;

import java.util.LinkedList;


/**
 * <p/>
 * Implements a synchronized, two-level priority queue of events to be
 * delivered to entities by the Engine.
 * </p>
 * <p/>
 * <p/>
 * Internal events, i.e. events generated by an entity for delivery to itself
 * to force an immediate state change, take precedence over Normal events
 * (events generated outside the engine or by one entity for delivery to
 * another).
 * </p>
 *
 * @author Pete Ford, May 30, 2005 &copy;Pete Ford &amp; CodeXombie.com 2005
 */

//**********************************************
//
//This package is rebundled after the code from JSpasm
//
// Project Homepage : http://jspasm.sourceforge.net/
// Original Developer : Pete Ford
// Official Domain : CodeXombie.com
//
//**********************************************

final class EventQueue {
    /**
     * <p/>
     * The high-priority internal event list.
     * </p>
     */
    private LinkedList internalQueue;

    /**
     * <p/>
     * The normal-priority event list.
     * </p>
     */
    private LinkedList normalQueue;

    /**
     * <p/>
     * Constructor.
     * </p>
     */
    EventQueue() {
        internalQueue = new LinkedList();
        normalQueue = new LinkedList();
    }

    /**
     * <p/>
     * Removes and returns the next event from the queue. Internal events are
     * always taken first; normal events are selected only when there are no
     * internal events. Aside from this constraint, events are always taken in
     * the same order that they were queued.
     * </p>
     * <p/>
     * <p/>
     * If there are no events of either kind in the queue, the calling thread
     * is blocked until another thread queues an event or an interrupt is
     * received.
     * </p>
     *
     * @return The next event.
     * @throws InterruptedException DOCUMENT ME!
     */
    Event dequeue() throws InterruptedException {
        Event event;

        synchronized (this) {
            while ((internalQueue.isEmpty()) && (normalQueue.isEmpty())) {
                wait();
            }

            if (!internalQueue.isEmpty()) {
                event = (Event) internalQueue.removeFirst();
            } else {
                event = (Event) normalQueue.removeFirst();
            }
        }

        return event;
    }

    /**
     * <p/>
     * Queues an event at normal priority. If the engine thread is blocked
     * waiting for an event, it will be notified and unblocked.
     * </p>
     *
     * @param event The event to queue.
     */
    void queueNormal(Event event) {
        synchronized (this) {
            normalQueue.addLast(event);
            notifyAll();
        }
    }

    /**
     * <p/>
     * Queues an event at high priority. If the engine thread is blocked
     * waiting for an event, it will be notified and unblocked.
     * </p>
     *
     * @param event The event to queue.
     */
    void queueInternal(Event event) {
        synchronized (this) {
            internalQueue.addLast(event);
            notifyAll();
        }
    }
}
